'use client'

import Link from 'next/link'
import styles from '@/components/deal-room/deal-room.module.css'
import { TrackPageView } from '@/components/tracking/TrackPageView'

// ── Types ────────────────────────────────────────────────────────────────────

type FileStatus = 'complete' | 'pending' | 'missing' | 'draft'
type FileIconType = 'folder' | 'pdf' | 'doc' | 'xls' | 'img' | 'other'

interface FileRow {
  name: string
  meta?: string
  iconType: FileIconType
  status: FileStatus
  size: string
  updated: string
  shared?: { initials: string; color: string }[]
  missing?: boolean
}

interface CategoryCard {
  name: string
  count: string
  iconColor: string
  iconBg: string
  barColor?: string
  barPct?: number
  active?: boolean
}

interface ActivityItem {
  text: string
  who: string
  action: string
  time: string
  iconBg: string
  iconColor: string
  iconType: 'view' | 'download' | 'upload' | 'share'
}

interface ChecklistRow {
  label: string
  done: boolean
}

interface SharedUser {
  initials: string
  color: string
  name: string
  access: string
  views: number
}

// ── Data ─────────────────────────────────────────────────────────────────────

// Category-specific SVG icons matching mocksite data-room.html exactly
function CategoryIcon({ name }: { name: string }) {
  switch (name) {
    case 'Financial':
      return (
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
          <line x1="12" y1="1" x2="12" y2="23"/>
          <path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/>
        </svg>
      )
    case 'Legal':
      return (
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
          <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
          <polyline points="14 2 14 8 20 8"/>
        </svg>
      )
    case 'HR & Team':
      return (
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
          <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/>
          <circle cx="9" cy="7" r="4"/>
        </svg>
      )
    case 'Operations':
      return (
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
          <circle cx="12" cy="12" r="10"/>
          <polyline points="12 6 12 12 16 14"/>
        </svg>
      )
    case 'Compliance':
      return (
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
          <rect x="3" y="11" width="18" height="11" rx="2" ry="2"/>
          <path d="M7 11V7a5 5 0 0110 0v4"/>
        </svg>
      )
    default:
      // All Files — folder icon
      return (
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
          <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z"/>
        </svg>
      )
  }
}

const CATEGORIES: CategoryCard[] = [
  { name: 'All Files', count: '38 documents', iconColor: 'var(--accent)', iconBg: 'var(--accent-light)', active: true },
  { name: 'Financial', count: '12 of 15', iconColor: 'var(--green)', iconBg: 'var(--green-light)', barColor: 'var(--green)', barPct: 80 },
  { name: 'Legal', count: '8 of 12', iconColor: 'var(--purple)', iconBg: 'var(--purple-light)', barColor: 'var(--purple)', barPct: 67 },
  { name: 'HR & Team', count: '6 of 8', iconColor: 'var(--orange)', iconBg: 'var(--orange-light)', barColor: 'var(--orange)', barPct: 75 },
  { name: 'Operations', count: '7 of 8', iconColor: 'var(--teal)', iconBg: 'var(--teal-light)', barColor: '#5AC8FA', barPct: 88 },
  { name: 'Compliance', count: '5 of 6', iconColor: 'var(--red)', iconBg: 'var(--red-light)', barColor: 'var(--red)', barPct: 83 },
]

const FILES: FileRow[] = [
  {
    name: 'Tax Returns',
    meta: '4 files',
    iconType: 'folder',
    status: 'complete',
    size: '8.4 MB',
    updated: 'Feb 10, 2026',
    shared: [
      { initials: 'SM', color: '#4A90D9' },
      { initials: 'JK', color: '#7B61FF' },
    ],
  },
  {
    name: 'Profit & Loss Statement (3-Year)',
    meta: 'XLSX · Auto-synced from QuickBooks',
    iconType: 'xls',
    status: 'complete',
    size: '1.2 MB',
    updated: 'Feb 12, 2026',
    shared: [{ initials: 'SM', color: '#4A90D9' }],
  },
  {
    name: 'Balance Sheet (3-Year)',
    meta: 'XLSX · Auto-synced from QuickBooks',
    iconType: 'xls',
    status: 'complete',
    size: '856 KB',
    updated: 'Feb 12, 2026',
    shared: [{ initials: 'SM', color: '#4A90D9' }],
  },
  {
    name: 'Cash Flow Statement',
    meta: 'XLSX · Auto-synced from QuickBooks',
    iconType: 'xls',
    status: 'complete',
    size: '640 KB',
    updated: 'Feb 12, 2026',
  },
  {
    name: 'AR Aging Report',
    meta: 'PDF · Manually uploaded',
    iconType: 'pdf',
    status: 'pending',
    size: '320 KB',
    updated: 'Feb 8, 2026',
  },
  {
    name: 'EBITDA Adjustments Schedule',
    meta: 'DOCX · Generated by Exit OS',
    iconType: 'doc',
    status: 'complete',
    size: '245 KB',
    updated: 'Feb 14, 2026',
    shared: [
      { initials: 'SM', color: '#4A90D9' },
      { initials: 'JK', color: '#7B61FF' },
      { initials: 'TL', color: '#FF6B6B' },
    ],
  },
  { name: 'Revenue Breakdown by Customer', meta: 'Required for due diligence', iconType: 'other', status: 'missing', size: '—', updated: '—', missing: true },
  { name: '3-Year Financial Projections', meta: 'Required for due diligence', iconType: 'other', status: 'missing', size: '—', updated: '—', missing: true },
  { name: 'Debt & Loan Schedule', meta: 'Required for due diligence', iconType: 'other', status: 'missing', size: '—', updated: '—', missing: true },
]

const ACTIVITY: ActivityItem[] = [
  { who: 'ServiceMaster PE', action: 'viewed Tax Returns', time: '2 hours ago', iconBg: 'var(--accent-light)', iconColor: 'var(--accent)', iconType: 'view', text: '' },
  { who: 'ServiceMaster PE', action: 'downloaded P&L Statement', time: '3 hours ago', iconBg: 'var(--green-light)', iconColor: 'var(--green)', iconType: 'download', text: '' },
  { who: 'You', action: 'uploaded EBITDA Adjustments', time: 'Yesterday', iconBg: 'var(--purple-light)', iconColor: 'var(--purple)', iconType: 'upload', text: '' },
  { who: 'You', action: 'shared folder with Jeff Kim (Attorney)', time: '2 days ago', iconBg: 'var(--orange-light)', iconColor: 'var(--orange)', iconType: 'share', text: '' },
  { who: 'ComfortCore HVAC', action: 'viewed Balance Sheet', time: '3 days ago', iconBg: 'var(--accent-light)', iconColor: 'var(--accent)', iconType: 'view', text: '' },
]

const CHECKLIST: ChecklistRow[] = [
  { label: '3-year financial statements', done: true },
  { label: 'Tax returns (3 years)', done: true },
  { label: 'EBITDA adjustments schedule', done: true },
  { label: 'Revenue by customer breakdown', done: false },
  { label: '3-year financial projections', done: false },
  { label: 'Employee roster & org chart', done: true },
  { label: 'Articles of incorporation', done: true },
  { label: 'Debt & loan schedule', done: false },
]

const SHARED_USERS: SharedUser[] = [
  { initials: 'SM', color: '#4A90D9', name: 'ServiceMaster PE', access: 'Full Access', views: 38 },
  { initials: 'JK', color: '#7B61FF', name: 'Jeff Kim (Attorney)', access: 'Full Access', views: 12 },
  { initials: 'TL', color: '#FF6B6B', name: 'Tom Liu (CPA)', access: 'Financial Only', views: 5 },
]

// ── Sub-components ────────────────────────────────────────────────────────────

function FileIconSvg() {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}

function FolderIconSvg() {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z" />
    </svg>
  )
}

function FileIconEl({ type }: { type: FileIconType }) {
  const cls = `${styles.fileIcon} ${
    type === 'folder' ? styles.fileIconFolder :
    type === 'pdf'    ? styles.fileIconPdf :
    type === 'doc'    ? styles.fileIconDoc :
    type === 'xls'    ? styles.fileIconXls :
    type === 'img'    ? styles.fileIconImg :
    styles.fileIconOther
  }`
  return (
    <div className={cls}>
      {type === 'folder' ? <FolderIconSvg /> : <FileIconSvg />}
    </div>
  )
}

function StatusBadge({ status }: { status: FileStatus }) {
  const cls = `${styles.statusBadge} ${
    status === 'complete' ? styles.statusBadgeComplete :
    status === 'pending'  ? styles.statusBadgePending :
    status === 'missing'  ? styles.statusBadgeMissing :
    styles.statusBadgeDraft
  }`
  const label = status === 'complete' ? 'Complete' : status === 'pending' ? 'Review' : status === 'missing' ? 'Missing' : 'Draft'
  return (
    <span className={cls}>
      <span className={styles.statusDot} />
      {label}
    </span>
  )
}

function ActivityIcon({ type, bg, color }: { type: ActivityItem['iconType']; bg: string; color: string }) {
  const viewIcon = (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
      <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
  const downloadIcon = (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
      <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  )
  const uploadIcon = (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
      <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" y1="3" x2="12" y2="15" />
    </svg>
  )
  const shareIcon = (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
      <circle cx="18" cy="5" r="3" />
      <circle cx="6" cy="12" r="3" />
      <circle cx="18" cy="19" r="3" />
      <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
      <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
    </svg>
  )
  const icon = type === 'view' ? viewIcon : type === 'download' ? downloadIcon : type === 'upload' ? uploadIcon : shareIcon
  return (
    <div className={styles.drActivityIcon} style={{ background: bg, color }}>
      {icon}
    </div>
  )
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function DataRoomPage() {
  return (
    <>
      <TrackPageView page="data-room" />

      {/* Top Bar */}
      <div className={styles.topBar}>
        <div className={styles.pageTitle}>
          <h1>Data Room</h1>
          <p>Organize and share due diligence documents securely with buyers</p>
        </div>
        <div className={styles.topActions}>
          <button className={`${styles.btn} ${styles.btnSecondary}`}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
              <polyline points="17 8 12 3 7 8" />
              <line x1="12" y1="3" x2="12" y2="15" />
            </svg>
            Upload Files
          </button>
          <button className={`${styles.btn} ${styles.btnPrimary}`}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
              <circle cx="18" cy="5" r="3" />
              <circle cx="6" cy="12" r="3" />
              <circle cx="18" cy="19" r="3" />
              <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
              <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
            </svg>
            Share Data Room
          </button>
        </div>
      </div>

      {/* Readiness Banner */}
      <div className={styles.readinessBanner}>
        <div className={styles.readinessLeft}>
          <h3>Data Room Completeness</h3>
          <p>Your data room is 72% ready for due diligence. 11 documents still needed.</p>
          <div className={styles.readinessProgress}>
            <div className={styles.readinessFill} style={{ width: '72%' }} />
          </div>
        </div>
        <div className={styles.readinessStats}>
          <div className={styles.readinessStat}>
            <div className="val" style={{ fontSize: 28, fontWeight: 700 }}>38</div>
            <div className="label" style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'rgba(255,255,255,0.5)' }}>Uploaded</div>
          </div>
          <div className={styles.readinessStat}>
            <div className="val" style={{ fontSize: 28, fontWeight: 700 }}>11</div>
            <div className="label" style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'rgba(255,255,255,0.5)' }}>Missing</div>
          </div>
          <div className={styles.readinessStat}>
            <div className="val" style={{ fontSize: 28, fontWeight: 700 }}>3</div>
            <div className="label" style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.5px', color: 'rgba(255,255,255,0.5)' }}>Shared</div>
          </div>
        </div>
      </div>

      {/* Category Cards */}
      <div className={styles.categoriesGrid}>
        {CATEGORIES.map((cat) => (
          <div key={cat.name} className={`${styles.categoryCard} ${cat.active ? styles.categoryCardActive : ''}`}>
            <div className={styles.categoryIcon} style={{ background: cat.iconBg, color: cat.iconColor }}>
              <CategoryIcon name={cat.name} />
            </div>
            <div className={styles.categoryName}>{cat.name}</div>
            <div className={styles.categoryCount}>{cat.count}</div>
            {cat.barColor && cat.barPct !== undefined && (
              <div className={styles.categoryBar}>
                <div className={styles.categoryBarFill} style={{ width: `${cat.barPct}%`, background: cat.barColor }} />
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Breadcrumb & Filter */}
      <div className={styles.breadcrumb}>
        <span style={{ color: 'var(--accent)', fontWeight: 500 }}>Data Room</span>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
          <polyline points="9 18 15 12 9 6" />
        </svg>
        <span>Financial Documents</span>
      </div>

      <div className={styles.drFilterBar}>
        <select className={styles.filterSelect}>
          <option>All Statuses</option>
          <option>Complete</option>
          <option>Pending Review</option>
          <option>Missing</option>
        </select>
        <select className={styles.filterSelect}>
          <option>Sort: Name A-Z</option>
          <option>Sort: Recently Updated</option>
          <option>Sort: Size</option>
        </select>
        <input type="text" className={styles.searchInput} placeholder="Search documents..." />
      </div>

      {/* Content Grid */}
      <div className={styles.contentGrid}>

        {/* File Table + Upload Zone */}
        <div>
          <div className={styles.fileTable}>
            <table>
              <thead>
                <tr>
                  <th>Document</th>
                  <th>Status</th>
                  <th>Size</th>
                  <th>Updated</th>
                  <th>Shared</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {FILES.map((file) => (
                  <tr key={file.name}>
                    <td>
                      <div className={styles.fileName}>
                        <FileIconEl type={file.iconType} />
                        <div>
                          <div style={{ color: file.missing ? 'var(--text-tertiary)' : undefined }}>{file.name}</div>
                          {file.meta && <div className={styles.fileMeta}>{file.meta}</div>}
                        </div>
                      </div>
                    </td>
                    <td><StatusBadge status={file.status} /></td>
                    <td style={{ fontSize: 13, color: file.missing ? 'var(--text-tertiary)' : 'var(--text-secondary)' }}>{file.size}</td>
                    <td style={{ fontSize: 13, color: file.missing ? 'var(--text-tertiary)' : 'var(--text-secondary)' }}>{file.updated}</td>
                    <td>
                      {file.shared && (
                        <div className={styles.sharedWith}>
                          {file.shared.map((s) => (
                            <div key={s.initials} className={styles.sharedAvatar} style={{ background: s.color }}>
                              {s.initials}
                            </div>
                          ))}
                        </div>
                      )}
                    </td>
                    <td>
                      <div className={styles.actionsCell}>
                        {file.missing ? (
                          <button className={styles.actionBtn} style={{ borderColor: 'var(--accent)', color: 'var(--accent)' }}>
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                              <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                              <polyline points="17 8 12 3 7 8" />
                              <line x1="12" y1="3" x2="12" y2="15" />
                            </svg>
                          </button>
                        ) : (
                          <>
                            <button className={styles.actionBtn}>
                              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                                <polyline points="7 10 12 15 17 10" />
                                <line x1="12" y1="15" x2="12" y2="3" />
                              </svg>
                            </button>
                            <button className={styles.actionBtn}>
                              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                                <circle cx="12" cy="12" r="1" />
                                <circle cx="19" cy="12" r="1" />
                                <circle cx="5" cy="12" r="1" />
                              </svg>
                            </button>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Upload Zone */}
          <div className={styles.uploadZone}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
              <polyline points="17 8 12 3 7 8" />
              <line x1="12" y1="3" x2="12" y2="15" />
            </svg>
            <p>Drag &amp; drop files here, or click to browse</p>
            <span>PDF, DOCX, XLSX, CSV, JPG up to 25 MB each</span>
          </div>
        </div>

        {/* Right Sidebar */}
        <div>

          {/* DD Checklist */}
          <div className={styles.drCard} style={{ marginBottom: 20 }}>
            <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 14 }}>Due Diligence Checklist</h3>
            {CHECKLIST.map((item) => (
              <div key={item.label} className={`${styles.checklistItem} ${item.done ? styles.checklistItemDone : ''}`}>
                <div className={`${styles.checkCircle} ${item.done ? styles.checkCircleDone : ''}`}>
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={3} strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                </div>
                <span>{item.label}</span>
              </div>
            ))}
          </div>

          {/* Recent Activity */}
          <div className={styles.drCard} style={{ marginBottom: 20 }}>
            <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 14 }}>Recent Activity</h3>
            {ACTIVITY.map((item, i) => (
              <div key={i} className={styles.drActivityItem}>
                <ActivityIcon type={item.iconType} bg={item.iconBg} color={item.iconColor} />
                <div>
                  <div className={styles.drActivityText}>
                    <strong>{item.who}</strong> {item.action}
                  </div>
                  <div className={styles.drActivityTime}>{item.time}</div>
                </div>
              </div>
            ))}
          </div>

          {/* Shared Access */}
          <div className={styles.drCard}>
            <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 14 }}>Shared Access</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {SHARED_USERS.map((u) => (
                <div key={u.initials} className={styles.sharedAccessRow}>
                  <div className={styles.sharedAccessAvatar} style={{ background: u.color }}>
                    {u.initials}
                  </div>
                  <div style={{ flex: 1 }}>
                    <div className={styles.sharedAccessName}>{u.name}</div>
                    <div className={styles.sharedAccessMeta}>{u.access} &middot; {u.views} views</div>
                  </div>
                  <span className={`${styles.statusBadge} ${styles.statusBadgeComplete}`} style={{ fontSize: 11 }}>
                    <span className={styles.statusDot} />
                    Active
                  </span>
                </div>
              ))}
            </div>
            <button className={`${styles.btn} ${styles.btnSecondary}`} style={{ width: '100%', marginTop: 14, justifyContent: 'center' }}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} style={{ width: 14, height: 14 }}>
                <line x1="12" y1="5" x2="12" y2="19" />
                <line x1="5" y1="12" x2="19" y2="12" />
              </svg>
              Invite Someone
            </button>
          </div>

        </div>
      </div>
    </>
  )
}
