// Industry Multiples Seed Data for Exit OSx
// Based on SMB M&A market data for small-to-medium businesses
// EBITDA multiples typically range 3x-8x for SMBs, with software/SaaS higher
// EBITDA margins are decimals (0.15 = 15%) — consistent with multiple-research-engine output

export interface IndustryMultipleData {
  icbIndustry: string
  icbSuperSector: string
  icbSector: string
  icbSubSector: string
  revenueMultipleLow: number
  revenueMultipleHigh: number
  ebitdaMultipleLow: number
  ebitdaMultipleHigh: number
  ebitdaMarginLow: number
  ebitdaMarginHigh: number
  effectiveDate: Date
  source: string
}

const effectiveDate = new Date('2024-01-01')
const source = 'SMB M&A Market Data 2024'

export const industryMultiples: IndustryMultipleData[] = [
  // ============================================
  // TECHNOLOGY
  // ============================================

  // Software - Higher multiples and margins for recurring revenue
  {
    icbIndustry: 'TECHNOLOGY',
    icbSuperSector: 'SOFTWARE_SERVICES',
    icbSector: 'SOFTWARE',
    icbSubSector: 'CONSUMER_SOFTWARE',
    revenueMultipleLow: 1.5,
    revenueMultipleHigh: 3.0,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'TECHNOLOGY',
    icbSuperSector: 'SOFTWARE_SERVICES',
    icbSector: 'SOFTWARE',
    icbSubSector: 'ENTERPRISE_SOFTWARE',
    revenueMultipleLow: 2.0,
    revenueMultipleHigh: 4.0,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 10.0,
    ebitdaMarginLow: 0.18,
    ebitdaMarginHigh: 0.3,
    effectiveDate,
    source,
  },

  // IT Services
  {
    icbIndustry: 'TECHNOLOGY',
    icbSuperSector: 'SOFTWARE_SERVICES',
    icbSector: 'IT_SERVICES',
    icbSubSector: 'IT_CONSULTING',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'TECHNOLOGY',
    icbSuperSector: 'SOFTWARE_SERVICES',
    icbSector: 'IT_SERVICES',
    icbSubSector: 'DATA_PROCESSING',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.22,
    effectiveDate,
    source,
  },

  // Tech Hardware - Lower margins due to hardware costs
  {
    icbIndustry: 'TECHNOLOGY',
    icbSuperSector: 'TECH_HARDWARE',
    icbSector: 'SEMICONDUCTORS',
    icbSubSector: 'SEMICONDUCTORS_SUB',
    revenueMultipleLow: 1.5,
    revenueMultipleHigh: 3.0,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'TECHNOLOGY',
    icbSuperSector: 'TECH_HARDWARE',
    icbSector: 'ELECTRONICS',
    icbSubSector: 'ELECTRONIC_COMPONENTS',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'TECHNOLOGY',
    icbSuperSector: 'TECH_HARDWARE',
    icbSector: 'ELECTRONICS',
    icbSubSector: 'ELECTRONIC_MANUFACTURING',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.06,
    ebitdaMarginHigh: 0.12,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'TECHNOLOGY',
    icbSuperSector: 'TECH_HARDWARE',
    icbSector: 'TECH_HARDWARE_EQUIP',
    icbSubSector: 'COMPUTER_HARDWARE',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.14,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'TECHNOLOGY',
    icbSuperSector: 'TECH_HARDWARE',
    icbSector: 'TECH_HARDWARE_EQUIP',
    icbSubSector: 'ELECTRONIC_OFFICE',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 5.5,
    ebitdaMarginLow: 0.06,
    ebitdaMarginHigh: 0.12,
    effectiveDate,
    source,
  },

  // ============================================
  // HEALTHCARE
  // ============================================

  {
    icbIndustry: 'HEALTHCARE',
    icbSuperSector: 'HEALTHCARE_PROVIDERS',
    icbSector: 'HEALTH_CARE_SERVICES',
    icbSubSector: 'HEALTHCARE_FACILITIES',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'HEALTHCARE',
    icbSuperSector: 'HEALTHCARE_PROVIDERS',
    icbSector: 'HEALTH_CARE_SERVICES',
    icbSubSector: 'HEALTHCARE_MANAGEMENT',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 5.5,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'HEALTHCARE',
    icbSuperSector: 'MEDICAL_EQUIPMENT',
    icbSector: 'MEDICAL_EQUIP_SERVICES',
    icbSubSector: 'MEDICAL_EQUIPMENT_SUB',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'HEALTHCARE',
    icbSuperSector: 'MEDICAL_EQUIPMENT',
    icbSector: 'MEDICAL_SUPPLIES',
    icbSubSector: 'MEDICAL_SUPPLIES_SUB',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'HEALTHCARE',
    icbSuperSector: 'PHARMA_BIOTECH',
    icbSector: 'PHARMA',
    icbSubSector: 'PHARMA_SUB',
    revenueMultipleLow: 1.5,
    revenueMultipleHigh: 3.0,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 10.0,
    ebitdaMarginLow: 0.18,
    ebitdaMarginHigh: 0.3,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'HEALTHCARE',
    icbSuperSector: 'PHARMA_BIOTECH',
    icbSector: 'BIOTECH',
    icbSubSector: 'BIOTECH_SUB',
    revenueMultipleLow: 2.0,
    revenueMultipleHigh: 5.0,
    ebitdaMultipleLow: 7.0,
    ebitdaMultipleHigh: 12.0,
    ebitdaMarginLow: 0.2,
    ebitdaMarginHigh: 0.35,
    effectiveDate,
    source,
  },

  // ============================================
  // CONSUMER DISCRETIONARY
  // ============================================

  // Retail - Lower margins due to competition and inventory costs
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'RETAIL',
    icbSector: 'GENERAL_RETAIL',
    icbSubSector: 'BROADLINE_RETAIL',
    revenueMultipleLow: 0.3,
    revenueMultipleHigh: 0.6,
    ebitdaMultipleLow: 3.0,
    ebitdaMultipleHigh: 5.0,
    ebitdaMarginLow: 0.04,
    ebitdaMarginHigh: 0.08,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'RETAIL',
    icbSector: 'GENERAL_RETAIL',
    icbSubSector: 'DISCOUNT_RETAIL',
    revenueMultipleLow: 0.2,
    revenueMultipleHigh: 0.5,
    ebitdaMultipleLow: 3.0,
    ebitdaMultipleHigh: 5.0,
    ebitdaMarginLow: 0.03,
    ebitdaMarginHigh: 0.06,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'RETAIL',
    icbSector: 'SPECIALTY_RETAIL',
    icbSubSector: 'APPAREL_RETAIL',
    revenueMultipleLow: 0.3,
    revenueMultipleHigh: 0.7,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 5.5,
    ebitdaMarginLow: 0.05,
    ebitdaMarginHigh: 0.1,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'RETAIL',
    icbSector: 'SPECIALTY_RETAIL',
    icbSubSector: 'HOME_IMPROVEMENT',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.06,
    ebitdaMarginHigh: 0.12,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'RETAIL',
    icbSector: 'SPECIALTY_RETAIL',
    icbSubSector: 'SPECIALTY_STORES',
    revenueMultipleLow: 0.3,
    revenueMultipleHigh: 0.6,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 5.5,
    ebitdaMarginLow: 0.05,
    ebitdaMarginHigh: 0.1,
    effectiveDate,
    source,
  },

  // Travel & Leisure
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'TRAVEL_LEISURE',
    icbSector: 'HOTELS_ENTERTAINMENT',
    icbSubSector: 'CASINOS_GAMING',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'TRAVEL_LEISURE',
    icbSector: 'HOTELS_ENTERTAINMENT',
    icbSubSector: 'HOTELS_MOTELS',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.2,
    ebitdaMarginHigh: 0.3,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'TRAVEL_LEISURE',
    icbSector: 'HOTELS_ENTERTAINMENT',
    icbSubSector: 'LEISURE_FACILITIES',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.5,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'TRAVEL_LEISURE',
    icbSector: 'RESTAURANTS_BARS',
    icbSubSector: 'RESTAURANTS',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 5.5,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'TRAVEL_LEISURE',
    icbSector: 'TRAVEL_TOURISM',
    icbSubSector: 'TRAVEL_SERVICES',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },

  // Media
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'MEDIA',
    icbSector: 'MEDIA_AGENCIES',
    icbSubSector: 'ADVERTISING',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'MEDIA',
    icbSector: 'MEDIA_AGENCIES',
    icbSubSector: 'MARKETING_PR',
    revenueMultipleLow: 0.7,
    revenueMultipleHigh: 1.3,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.5,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'MEDIA',
    icbSector: 'PUBLISHING',
    icbSubSector: 'PUBLISHING_SUB',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'MEDIA',
    icbSector: 'BROADCASTING',
    icbSubSector: 'BROADCASTING_SUB',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'MEDIA',
    icbSector: 'BROADCASTING',
    icbSubSector: 'ENTERTAINMENT_PROD',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },

  // Automobiles
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'AUTOMOBILES',
    icbSector: 'AUTO_PARTS',
    icbSubSector: 'AUTO_PARTS_SUB',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.14,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'AUTOMOBILES',
    icbSector: 'AUTO_RETAIL_SERVICE',
    icbSubSector: 'AUTO_RETAIL',
    revenueMultipleLow: 0.2,
    revenueMultipleHigh: 0.4,
    ebitdaMultipleLow: 3.0,
    ebitdaMultipleHigh: 5.0,
    ebitdaMarginLow: 0.03,
    ebitdaMarginHigh: 0.06,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'AUTOMOBILES',
    icbSector: 'AUTO_RETAIL_SERVICE',
    icbSubSector: 'AUTO_SERVICE',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 5.5,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },

  // Consumer Products
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'CONSUMER_PRODUCTS',
    icbSector: 'HOUSEHOLD_GOODS',
    icbSubSector: 'HOME_CONSTRUCTION',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'CONSUMER_PRODUCTS',
    icbSector: 'HOUSEHOLD_GOODS',
    icbSubSector: 'HOME_FURNISHINGS',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 5.5,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.14,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'CONSUMER_PRODUCTS',
    icbSector: 'HOUSEHOLD_GOODS',
    icbSubSector: 'HOUSEHOLD_APPLIANCES',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.14,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'CONSUMER_PRODUCTS',
    icbSector: 'LEISURE_GOODS',
    icbSubSector: 'CONSUMER_ELECTRONICS',
    revenueMultipleLow: 0.3,
    revenueMultipleHigh: 0.6,
    ebitdaMultipleLow: 3.0,
    ebitdaMultipleHigh: 5.0,
    ebitdaMarginLow: 0.05,
    ebitdaMarginHigh: 0.1,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'CONSUMER_PRODUCTS',
    icbSector: 'LEISURE_GOODS',
    icbSubSector: 'RECREATIONAL_PRODUCTS',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 5.5,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.14,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'CONSUMER_PRODUCTS',
    icbSector: 'PERSONAL_GOODS',
    icbSubSector: 'CLOTHING_ACCESSORIES',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_DISCRETIONARY',
    icbSuperSector: 'CONSUMER_PRODUCTS',
    icbSector: 'PERSONAL_GOODS',
    icbSubSector: 'FOOTWEAR',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.16,
    effectiveDate,
    source,
  },

  // ============================================
  // CONSUMER STAPLES
  // ============================================

  {
    icbIndustry: 'CONSUMER_STAPLES',
    icbSuperSector: 'FOOD_BEVERAGE',
    icbSector: 'BEVERAGES',
    icbSubSector: 'BREWERS',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.22,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_STAPLES',
    icbSuperSector: 'FOOD_BEVERAGE',
    icbSector: 'BEVERAGES',
    icbSubSector: 'DISTILLERS_VINTNERS',
    revenueMultipleLow: 1.2,
    revenueMultipleHigh: 2.5,
    ebitdaMultipleLow: 6.5,
    ebitdaMultipleHigh: 10.0,
    ebitdaMarginLow: 0.18,
    ebitdaMarginHigh: 0.28,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_STAPLES',
    icbSuperSector: 'FOOD_BEVERAGE',
    icbSector: 'BEVERAGES',
    icbSubSector: 'SOFT_DRINKS',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_STAPLES',
    icbSuperSector: 'FOOD_BEVERAGE',
    icbSector: 'FOOD_PRODUCERS',
    icbSubSector: 'AGRICULTURAL_PRODUCTS',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.06,
    ebitdaMarginHigh: 0.12,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_STAPLES',
    icbSuperSector: 'FOOD_BEVERAGE',
    icbSector: 'FOOD_PRODUCERS',
    icbSubSector: 'PACKAGED_FOODS',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 7.5,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.16,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_STAPLES',
    icbSuperSector: 'PERSONAL_HOUSEHOLD',
    icbSector: 'FOOD_DRUG_RETAIL',
    icbSubSector: 'DRUG_RETAIL',
    revenueMultipleLow: 0.3,
    revenueMultipleHigh: 0.6,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.04,
    ebitdaMarginHigh: 0.08,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_STAPLES',
    icbSuperSector: 'PERSONAL_HOUSEHOLD',
    icbSector: 'FOOD_DRUG_RETAIL',
    icbSubSector: 'FOOD_DISTRIBUTORS',
    revenueMultipleLow: 0.2,
    revenueMultipleHigh: 0.5,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.03,
    ebitdaMarginHigh: 0.06,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_STAPLES',
    icbSuperSector: 'PERSONAL_HOUSEHOLD',
    icbSector: 'FOOD_DRUG_RETAIL',
    icbSubSector: 'FOOD_RETAIL',
    revenueMultipleLow: 0.2,
    revenueMultipleHigh: 0.4,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 5.5,
    ebitdaMarginLow: 0.02,
    ebitdaMarginHigh: 0.05,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'CONSUMER_STAPLES',
    icbSuperSector: 'PERSONAL_HOUSEHOLD',
    icbSector: 'PERSONAL_PRODUCTS',
    icbSubSector: 'PERSONAL_PRODUCTS_SUB',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },

  // ============================================
  // INDUSTRIALS
  // ============================================

  // Construction
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'CONSTRUCTION',
    icbSector: 'CONSTRUCTION_MATERIALS',
    icbSubSector: 'BUILDING_PRODUCTS',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'CONSTRUCTION',
    icbSector: 'CONSTRUCTION_MATERIALS',
    icbSubSector: 'CONSTRUCTION_SERVICES',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.06,
    ebitdaMarginHigh: 0.12,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'CONSTRUCTION',
    icbSector: 'CONSTRUCTION_MATERIALS',
    icbSubSector: 'CONSTRUCTION_MATERIALS_SUB',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 7.5,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },

  // Industrial Goods
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'AEROSPACE_DEFENSE',
    icbSubSector: 'AEROSPACE_DEFENSE_SUB',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'GENERAL_INDUSTRIALS',
    icbSubSector: 'DIVERSIFIED_INDUSTRIALS',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'ELECTRONIC_EQUIPMENT',
    icbSubSector: 'ELECTRICAL_COMPONENTS',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 7.5,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.16,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'INDUSTRIAL_ENGINEERING',
    icbSubSector: 'HEAVY_ELECTRICAL',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 7.5,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.14,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'INDUSTRIAL_ENGINEERING',
    icbSubSector: 'INDUSTRIAL_MACHINERY',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 7.5,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.16,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'INDUSTRIAL_SUPPORT',
    icbSubSector: 'BUSINESS_SUPPORT',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'INDUSTRIAL_SUPPORT',
    icbSubSector: 'COMMERCIAL_PRINTING',
    revenueMultipleLow: 0.3,
    revenueMultipleHigh: 0.6,
    ebitdaMultipleLow: 3.0,
    ebitdaMultipleHigh: 5.0,
    ebitdaMarginLow: 0.05,
    ebitdaMarginHigh: 0.1,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'INDUSTRIAL_SUPPORT',
    icbSubSector: 'ENVIRONMENTAL_SERVICES',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.5,
    ebitdaMultipleHigh: 8.5,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'INDUSTRIAL_SUPPORT',
    icbSubSector: 'PROFESSIONAL_SERVICES',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'INDUSTRIAL_SUPPORT',
    icbSubSector: 'SECURITY_ALARM',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_GOODS',
    icbSector: 'INDUSTRIAL_SUPPORT',
    icbSubSector: 'STAFFING',
    revenueMultipleLow: 0.3,
    revenueMultipleHigh: 0.6,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.5,
    ebitdaMarginLow: 0.03,
    ebitdaMarginHigh: 0.06,
    effectiveDate,
    source,
  },

  // Industrial Transport
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_TRANSPORT',
    icbSector: 'FREIGHT_LOGISTICS',
    icbSubSector: 'AIR_FREIGHT',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.05,
    ebitdaMarginHigh: 0.1,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_TRANSPORT',
    icbSector: 'FREIGHT_LOGISTICS',
    icbSubSector: 'MARINE_SHIPPING',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.5,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_TRANSPORT',
    icbSector: 'FREIGHT_LOGISTICS',
    icbSubSector: 'TRUCKING',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.05,
    ebitdaMarginHigh: 0.1,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_TRANSPORT',
    icbSector: 'PASSENGER_TRANSPORT',
    icbSubSector: 'AIRLINES',
    revenueMultipleLow: 0.3,
    revenueMultipleHigh: 0.6,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.05,
    ebitdaMarginHigh: 0.12,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'INDUSTRIALS',
    icbSuperSector: 'INDUSTRIAL_TRANSPORT',
    icbSector: 'PASSENGER_TRANSPORT',
    icbSubSector: 'RAILROADS',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.2,
    ebitdaMarginHigh: 0.35,
    effectiveDate,
    source,
  },

  // ============================================
  // FINANCIALS
  // ============================================

  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'FINANCIAL_SERVICES',
    icbSector: 'INVESTMENT_SERVICES',
    icbSubSector: 'ASSET_MANAGEMENT',
    revenueMultipleLow: 1.5,
    revenueMultipleHigh: 3.0,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 10.0,
    ebitdaMarginLow: 0.25,
    ebitdaMarginHigh: 0.4,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'FINANCIAL_SERVICES',
    icbSector: 'INVESTMENT_SERVICES',
    icbSubSector: 'INVESTMENT_BANKING',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.2,
    ebitdaMarginHigh: 0.35,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'FINANCIAL_SERVICES',
    icbSector: 'MORTGAGE_FINANCE',
    icbSubSector: 'MORTGAGE_FINANCE_SUB',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.5,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'FINANCIAL_SERVICES',
    icbSector: 'FINANCIAL_ADMIN',
    icbSubSector: 'FINANCIAL_DATA',
    revenueMultipleLow: 2.0,
    revenueMultipleHigh: 4.0,
    ebitdaMultipleLow: 7.0,
    ebitdaMultipleHigh: 12.0,
    ebitdaMarginLow: 0.25,
    ebitdaMarginHigh: 0.4,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'FINANCIAL_SERVICES',
    icbSector: 'FINANCIAL_ADMIN',
    icbSubSector: 'TRANSACTION_PROCESSING',
    revenueMultipleLow: 1.5,
    revenueMultipleHigh: 3.0,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 10.0,
    ebitdaMarginLow: 0.2,
    ebitdaMarginHigh: 0.35,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'INSURANCE',
    icbSector: 'LIFE_INSURANCE',
    icbSubSector: 'LIFE_INSURANCE_SUB',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'INSURANCE',
    icbSector: 'PROPERTY_INSURANCE',
    icbSubSector: 'PROPERTY_CASUALTY',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'INSURANCE',
    icbSector: 'PROPERTY_INSURANCE',
    icbSubSector: 'REINSURANCE',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.5,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'BANKS',
    icbSector: 'BANKING',
    icbSubSector: 'COMMERCIAL_BANKS',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.25,
    ebitdaMarginHigh: 0.4,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'FINANCIALS',
    icbSuperSector: 'BANKS',
    icbSector: 'BANKING',
    icbSubSector: 'COMMUNITY_BANKS',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.2,
    ebitdaMarginHigh: 0.35,
    effectiveDate,
    source,
  },

  // ============================================
  // REAL ESTATE
  // ============================================

  {
    icbIndustry: 'REAL_ESTATE',
    icbSuperSector: 'REAL_ESTATE_SERVICES',
    icbSector: 'REAL_ESTATE_HOLDING',
    icbSubSector: 'REAL_ESTATE_DEV',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'REAL_ESTATE',
    icbSuperSector: 'REAL_ESTATE_SERVICES',
    icbSector: 'REAL_ESTATE_HOLDING',
    icbSubSector: 'REAL_ESTATE_OPERATING',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.2,
    ebitdaMarginHigh: 0.35,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'REAL_ESTATE',
    icbSuperSector: 'REAL_ESTATE_SERVICES',
    icbSector: 'REAL_ESTATE_SERVICES_SEC',
    icbSubSector: 'REAL_ESTATE_BROKERAGE',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 3.5,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'REAL_ESTATE',
    icbSuperSector: 'REAL_ESTATE_SERVICES',
    icbSector: 'REAL_ESTATE_SERVICES_SEC',
    icbSubSector: 'PROPERTY_MANAGEMENT',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },

  // ============================================
  // UTILITIES
  // ============================================

  {
    icbIndustry: 'UTILITIES',
    icbSuperSector: 'UTILITIES_SERVICES',
    icbSector: 'ELECTRICITY',
    icbSubSector: 'ELECTRIC_UTILITIES',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.18,
    ebitdaMarginHigh: 0.28,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'UTILITIES',
    icbSuperSector: 'UTILITIES_SERVICES',
    icbSector: 'GAS_WATER',
    icbSubSector: 'GAS_UTILITIES',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.5,
    ebitdaMultipleHigh: 8.5,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'UTILITIES',
    icbSuperSector: 'UTILITIES_SERVICES',
    icbSector: 'GAS_WATER',
    icbSubSector: 'WATER_UTILITIES',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.2,
    ebitdaMarginHigh: 0.3,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'UTILITIES',
    icbSuperSector: 'UTILITIES_SERVICES',
    icbSector: 'GAS_WATER',
    icbSubSector: 'MULTI_UTILITIES',
    revenueMultipleLow: 0.9,
    revenueMultipleHigh: 1.8,
    ebitdaMultipleLow: 5.5,
    ebitdaMultipleHigh: 8.5,
    ebitdaMarginLow: 0.18,
    ebitdaMarginHigh: 0.28,
    effectiveDate,
    source,
  },

  // ============================================
  // BASIC MATERIALS
  // ============================================

  {
    icbIndustry: 'BASIC_MATERIALS',
    icbSuperSector: 'CHEMICALS',
    icbSector: 'CHEMICALS_SECTOR',
    icbSubSector: 'COMMODITY_CHEMICALS',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'BASIC_MATERIALS',
    icbSuperSector: 'CHEMICALS',
    icbSector: 'CHEMICALS_SECTOR',
    icbSubSector: 'SPECIALTY_CHEMICALS',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 5.5,
    ebitdaMultipleHigh: 8.5,
    ebitdaMarginLow: 0.12,
    ebitdaMarginHigh: 0.2,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'BASIC_MATERIALS',
    icbSuperSector: 'BASIC_RESOURCES',
    icbSector: 'FORESTRY_PAPER',
    icbSubSector: 'FOREST_PRODUCTS',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'BASIC_MATERIALS',
    icbSuperSector: 'BASIC_RESOURCES',
    icbSector: 'FORESTRY_PAPER',
    icbSubSector: 'PAPER_PRODUCTS',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.14,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'BASIC_MATERIALS',
    icbSuperSector: 'BASIC_RESOURCES',
    icbSector: 'INDUSTRIAL_METALS',
    icbSubSector: 'ALUMINUM',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.5,
    ebitdaMarginLow: 0.06,
    ebitdaMarginHigh: 0.12,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'BASIC_MATERIALS',
    icbSuperSector: 'BASIC_RESOURCES',
    icbSector: 'INDUSTRIAL_METALS',
    icbSubSector: 'STEEL',
    revenueMultipleLow: 0.4,
    revenueMultipleHigh: 0.8,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.0,
    ebitdaMarginLow: 0.06,
    ebitdaMarginHigh: 0.12,
    effectiveDate,
    source,
  },

  // ============================================
  // ENERGY
  // ============================================

  {
    icbIndustry: 'ENERGY',
    icbSuperSector: 'ENERGY_SERVICES',
    icbSector: 'OIL_GAS_COAL',
    icbSubSector: 'INTEGRATED_OIL',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 4.5,
    ebitdaMultipleHigh: 7.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'ENERGY',
    icbSuperSector: 'ENERGY_SERVICES',
    icbSector: 'OIL_GAS_COAL',
    icbSubSector: 'OIL_GAS_EXPLORATION',
    revenueMultipleLow: 0.8,
    revenueMultipleHigh: 1.5,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.5,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.3,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'ENERGY',
    icbSuperSector: 'ENERGY_SERVICES',
    icbSector: 'OIL_GAS_COAL',
    icbSubSector: 'OIL_GAS_SERVICES',
    revenueMultipleLow: 0.5,
    revenueMultipleHigh: 1.0,
    ebitdaMultipleLow: 4.0,
    ebitdaMultipleHigh: 6.5,
    ebitdaMarginLow: 0.08,
    ebitdaMarginHigh: 0.15,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'ENERGY',
    icbSuperSector: 'ENERGY_SERVICES',
    icbSector: 'ALTERNATIVE_ENERGY',
    icbSubSector: 'RENEWABLE_ENERGY',
    revenueMultipleLow: 1.5,
    revenueMultipleHigh: 3.0,
    ebitdaMultipleLow: 7.0,
    ebitdaMultipleHigh: 12.0,
    ebitdaMarginLow: 0.15,
    ebitdaMarginHigh: 0.25,
    effectiveDate,
    source,
  },

  // ============================================
  // TELECOMMUNICATIONS
  // ============================================

  {
    icbIndustry: 'TELECOMMUNICATIONS',
    icbSuperSector: 'TELECOM_SERVICES',
    icbSector: 'TELECOM_EQUIPMENT',
    icbSubSector: 'TELECOM_EQUIPMENT_SUB',
    revenueMultipleLow: 0.6,
    revenueMultipleHigh: 1.2,
    ebitdaMultipleLow: 5.0,
    ebitdaMultipleHigh: 8.0,
    ebitdaMarginLow: 0.1,
    ebitdaMarginHigh: 0.18,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'TELECOMMUNICATIONS',
    icbSuperSector: 'TELECOM_SERVICES',
    icbSector: 'TELECOM_PROVIDERS',
    icbSubSector: 'INTEGRATED_TELECOM',
    revenueMultipleLow: 1.0,
    revenueMultipleHigh: 2.0,
    ebitdaMultipleLow: 5.5,
    ebitdaMultipleHigh: 8.5,
    ebitdaMarginLow: 0.2,
    ebitdaMarginHigh: 0.3,
    effectiveDate,
    source,
  },
  {
    icbIndustry: 'TELECOMMUNICATIONS',
    icbSuperSector: 'TELECOM_SERVICES',
    icbSector: 'TELECOM_PROVIDERS',
    icbSubSector: 'WIRELESS_TELECOM',
    revenueMultipleLow: 1.2,
    revenueMultipleHigh: 2.5,
    ebitdaMultipleLow: 6.0,
    ebitdaMultipleHigh: 9.0,
    ebitdaMarginLow: 0.22,
    ebitdaMarginHigh: 0.35,
    effectiveDate,
    source,
  },
]
