// Playbook Definitions
// 44 pre-built playbooks with scoring triggers for the recommendation engine.
// Each playbook declares which DRS, RSS, and BQS signals make it relevant.
//
// DRS categories: FINANCIAL, TRANSFERABILITY, OPERATIONAL, MARKET, LEGAL_TAX, PERSONAL
// RSS discounts: Key-Person Risk, Customer Concentration, Documentation Quality, Legal/Tax Risk, Lack of Marketability (DLOM)
// BQS factors: owner_dependency, customer_concentration, recurring_revenue, growth_adjustment, margin_adjustment, size_discount

export type PlaybookCategory =
  | 'PERSONAL'
  | 'FINANCIAL'
  | 'OPERATIONAL'
  | 'LEGAL'
  | 'MARKET_GROWTH'
  | 'DEAL_PREP'

export type DifficultyLevel = 'NONE' | 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH'

export type TriggerSource = 'DRS' | 'RSS' | 'BQS'

export interface ScoringTrigger {
  source: TriggerSource
  signal: string
  weight: number
}

export interface PlaybookPhaseDefinition {
  title: string
  description: string
  order: number
}

export interface PlaybookDefinition {
  slug: string
  title: string
  category: PlaybookCategory
  difficulty: DifficultyLevel
  durationLow: number // months
  durationHigh: number // months
  description: string
  displayOrder: number
  triggers: ScoringTrigger[]
  impactBaseLow: number // normalized to $1M EBITDA
  impactBaseHigh: number // normalized to $1M EBITDA
  phases: PlaybookPhaseDefinition[]
}

export const playbookDefinitions: PlaybookDefinition[] = [
  // ==========================================
  // PERSONAL (01, 02, 04, 42)
  // ==========================================
  {
    slug: 'personal-financial-independence-assessment',
    title: 'Personal Financial Independence Assessment',
    category: 'PERSONAL',
    difficulty: 'MEDIUM',
    durationLow: 1,
    durationHigh: 3,
    description: 'Define your after-tax financial independence number by modeling post-exit spending, one-time costs, and legacy goals. Perform gap analysis against current assets and develop strategies to close any shortfall.',
    displayOrder: 1,
    triggers: [
      { source: 'DRS', signal: 'PERSONAL', weight: 0.60 },
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.40 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to the financial independence assessment.', order: 1 },
      { title: 'Why This Comes First', description: 'Understand why most owners plan backwards by starting with business value instead of personal need.', order: 2 },
      { title: 'Post-Exit Budget', description: 'Estimate annual spending after exit across core living, healthcare, travel, and lifestyle categories.', order: 3 },
      { title: 'One-Time Costs', description: 'Identify significant one-time expenditures planned after the sale closes.', order: 4 },
      { title: 'Legacy Goals', description: 'Define estate, charitable, education, and endowment goals.', order: 5 },
      { title: 'Your Number', description: 'Calculate the after-tax amount needed to fund your post-exit life indefinitely.', order: 6 },
      { title: 'Retirement Phases', description: 'Model three distinct spending phases with different spending patterns.', order: 7 },
      { title: 'Gap Analysis', description: 'Compare what you need against what you have.', order: 8 },
      { title: 'Closing the Gap', description: 'Select strategies to close the gap between your independence number and current assets.', order: 9 },
      { title: 'Advisor Team', description: 'Track engagement with wealth manager, tax attorney, and other essential advisors.', order: 10 },
      { title: 'Common Mistakes', description: 'Five pitfalls that derail even sophisticated business owners during exit planning.', order: 11 },
      { title: 'Implementation', description: 'A 6-month roadmap to fully define your financial independence number.', order: 12 },
      { title: 'Your Summary', description: 'Complete financial independence summary with calculations and action items.', order: 13 },
    ],
  },
  {
    slug: 'post-exit-identity-purpose-planning',
    title: 'Post-Exit Identity & Purpose Planning',
    category: 'PERSONAL',
    difficulty: 'MEDIUM',
    durationLow: 2,
    durationHigh: 6,
    description: 'Address the psychological dimension of exiting by building a compelling vision of life after the sale. Assess five pillars of post-exit identity and develop replacement plans for what the business currently provides.',
    displayOrder: 2,
    triggers: [
      { source: 'DRS', signal: 'PERSONAL', weight: 0.70 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.30 },
    ],
    impactBaseLow: 25_000,
    impactBaseHigh: 100_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to identity and purpose planning for life after exit.', order: 1 },
      { title: 'The Identity Crisis', description: 'Understand the identity crisis when decades of being "the owner" suddenly ends.', order: 2 },
      { title: 'What You Lose', description: 'Acknowledge each dimension of loss across status, routine, relationships, purpose, and competence.', order: 3 },
      { title: 'Self-Sabotage Check', description: 'Rate your tendency toward self-sabotaging behaviors.', order: 4 },
      { title: 'Five Pillars Assessment', description: 'Rate confidence across five pillars: purpose, structure, community, competence, and identity.', order: 5 },
      { title: 'Pillar Planning', description: 'For each pillar, identify what your business provides and what will replace it.', order: 6 },
      { title: 'Post-Exit Paths', description: 'Select from multiple post-exit paths that thriving former owners pursue.', order: 7 },
      { title: 'Emotional Timeline', description: 'Map the emotional journey of exiting to prepare for feelings at each stage.', order: 8 },
      { title: 'Pre-Exit Exploration', description: 'Start exploring 12-24 months before exit with practical research.', order: 9 },
      { title: '90-Day Plan', description: 'Draft a specific life plan for the first 90 days after close.', order: 10 },
      { title: 'Your Support Team', description: 'Engage executive coach, peer group, and spouse/partner.', order: 11 },
      { title: 'Common Mistakes', description: 'Common identity and purpose mistakes that lead to post-exit regret.', order: 12 },
      { title: 'Implementation', description: 'Timeline for executing identity and purpose planning milestones.', order: 13 },
      { title: 'Your New Identity', description: 'Write your new identity statement.', order: 14 },
      { title: 'Your Summary', description: 'Identity and purpose readiness summary.', order: 15 },
    ],
  },
  {
    slug: 'spousal-family-alignment',
    title: 'Spousal & Family Alignment',
    category: 'PERSONAL',
    difficulty: 'LOW',
    durationLow: 1,
    durationHigh: 3,
    description: 'Align your spouse/partner and family on the exit decision through structured conversations, partner alignment assessments, and ideal week comparisons.',
    displayOrder: 4,
    triggers: [
      { source: 'DRS', signal: 'PERSONAL', weight: 1.00 },
    ],
    impactBaseLow: 25_000,
    impactBaseHigh: 75_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to why family alignment is critical to a successful exit.', order: 1 },
      { title: 'Why Family Alignment Matters', description: 'Understand how misalignment derails exits and destroys value.', order: 2 },
      { title: 'The Alignment Conversation Framework', description: 'Structured framework for productive exit conversations with your partner.', order: 3 },
      { title: 'Partner Alignment Assessment', description: 'Assess alignment across financial, lifestyle, timing, and emotional dimensions.', order: 4 },
      { title: 'Ideal Week Comparison', description: 'Compare ideal post-exit weeks to find overlap and gaps.', order: 5 },
      { title: 'Children & Extended Family', description: 'Address considerations for children and extended family.', order: 6 },
      { title: 'Common Mistakes to Avoid', description: 'Common family alignment mistakes that torpedo deals.', order: 7 },
      { title: 'Family Alignment Dashboard', description: 'Summary showing alignment scores and conversation progress.', order: 8 },
    ],
  },
  {
    slug: 'deal-fatigue-management',
    title: 'Deal Fatigue Management',
    category: 'PERSONAL',
    difficulty: 'MEDIUM',
    durationLow: 1,
    durationHigh: 2,
    description: 'Manage the psychological and operational toll of a prolonged deal process. Covers the five stages of deal fatigue, maintaining business performance, stress management, and leverage preservation.',
    displayOrder: 42,
    triggers: [
      { source: 'DRS', signal: 'PERSONAL', weight: 0.60 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.40 },
    ],
    impactBaseLow: 25_000,
    impactBaseHigh: 100_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to deal fatigue and why it kills deals.', order: 1 },
      { title: 'Anatomy of Deal Fatigue', description: 'Understand the five predictable stages of deal fatigue.', order: 2 },
      { title: 'Building Your Deal Team', description: 'Build a team that carries operational burden.', order: 3 },
      { title: 'Business Performance', description: 'Maintain business performance during the deal.', order: 4 },
      { title: 'Stress & Mental Health', description: 'Manage the psychological impact of selling a business.', order: 5 },
      { title: 'Milestone Management', description: 'Set milestones for psychological momentum.', order: 6 },
      { title: 'Recovery Strategies', description: 'Diagnose why deals stall and apply recovery strategies.', order: 7 },
      { title: 'Maintaining Leverage', description: 'Preserve leverage when fatigued.', order: 8 },
      { title: 'Protecting Relationships', description: 'Manage relationships that deal fatigue can damage.', order: 9 },
      { title: 'Early Warning Checklist', description: 'Honest self-assessment of deal fatigue warning signs.', order: 10 },
      { title: 'Deal Fatigue Preparedness Dashboard', description: 'Overall deal fatigue preparedness score.', order: 11 },
    ],
  },

  // ==========================================
  // FINANCIAL (05-11, 28, 29)
  // ==========================================
  {
    slug: 'tax-estate-pre-planning',
    title: 'Tax & Estate Pre-Planning',
    category: 'FINANCIAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 12,
    description: 'Understand the tax landscape for business sales, evaluate entity structure and QSBS eligibility, explore tax minimization strategies, plan estate transfers, and calculate after-tax proceeds.',
    displayOrder: 5,
    triggers: [
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.50 },
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.30 },
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.20 },
    ],
    impactBaseLow: 100_000,
    impactBaseHigh: 500_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to tax and estate pre-planning.', order: 1 },
      { title: 'Tax Landscape', description: 'Federal and state tax implications for business sales.', order: 2 },
      { title: 'Entity & QSBS', description: 'Entity structure evaluation and QSBS eligibility.', order: 3 },
      { title: 'Tax Strategies', description: 'Tax minimization strategies including installment sales and opportunity zones.', order: 4 },
      { title: 'Estate Planning', description: 'Pre-exit estate planning including gifting strategies and trusts.', order: 5 },
      { title: 'Tax Calculator', description: 'Model after-tax proceeds under different structures.', order: 6 },
      { title: 'Pre-Exit Checklist', description: 'Comprehensive tax actions checklist.', order: 7 },
      { title: 'Common Mistakes', description: 'Tax planning mistakes that cost hundreds of thousands.', order: 8 },
      { title: 'Dashboard', description: 'Tax planning summary with checklist progress.', order: 9 },
    ],
  },
  {
    slug: 'financial-statement-cleanup',
    title: 'Financial Statement Cleanup & Audit Prep',
    category: 'FINANCIAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 9,
    description: 'Move from tax-return accounting to buyer-grade financials by assessing current state, optimizing chart of accounts, cleaning up revenue recognition and expense classification, and preparing for audited financials.',
    displayOrder: 6,
    triggers: [
      { source: 'RSS', signal: 'Documentation Quality', weight: 0.40 },
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.60 },
    ],
    impactBaseLow: 75_000,
    impactBaseHigh: 300_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to buyer-grade financials.', order: 1 },
      { title: 'Current State Assessment', description: 'Evaluate the current state of your financial statements.', order: 2 },
      { title: 'Chart of Accounts Optimization', description: 'Restructure chart of accounts to match buyer expectations.', order: 3 },
      { title: 'Revenue Recognition & Expense Classification', description: 'Clean up revenue recognition and expense classification.', order: 4 },
      { title: 'Balance Sheet Cleanup', description: 'Resolve balance sheet issues.', order: 5 },
      { title: 'The Path to Audited Financials', description: 'Prepare for the appropriate audit engagement.', order: 6 },
      { title: 'Implementation Action Plan', description: 'Step-by-step action plan with timelines.', order: 7 },
      { title: 'Financial Readiness Scorecard', description: 'Overall financial readiness score.', order: 8 },
    ],
  },
  {
    slug: 'ebitda-normalization',
    title: 'EBITDA Normalization & Add-Back Schedule',
    category: 'FINANCIAL',
    difficulty: 'HIGH',
    durationLow: 1,
    durationHigh: 3,
    description: 'Build the EBITDA bridge and add-back schedule. Identify defensible add-backs, flag aggressive adjustments buyers will reject, gather supporting evidence, and prepare for quality of earnings scrutiny.',
    displayOrder: 7,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.50 },
      { source: 'RSS', signal: 'Documentation Quality', weight: 0.30 },
      { source: 'BQS', signal: 'margin_adjustment', weight: 0.20 },
    ],
    impactBaseLow: 100_000,
    impactBaseHigh: 400_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to normalized EBITDA.', order: 1 },
      { title: 'Build Your EBITDA Bridge', description: 'Construct the bridge from reported net income to normalized EBITDA.', order: 2 },
      { title: 'Add-Back Schedule', description: 'Identify and categorize every potential add-back.', order: 3 },
      { title: 'Red Flag Review', description: 'Review add-backs for aggressive adjustments.', order: 4 },
      { title: 'Evidence Tracker', description: 'Gather supporting documentation for each add-back.', order: 5 },
      { title: 'Quality of Earnings Readiness', description: 'Prepare for the quality of earnings process.', order: 6 },
      { title: 'EBITDA Normalization Scorecard', description: 'Summary scorecard with normalized EBITDA.', order: 7 },
    ],
  },
  {
    slug: 'revenue-quality-analysis',
    title: 'Revenue Quality Analysis',
    category: 'FINANCIAL',
    difficulty: 'MEDIUM',
    durationLow: 1,
    durationHigh: 3,
    description: 'Analyze revenue quality across five tiers, assess recurring vs non-recurring ratios, measure customer concentration risk, evaluate diversification, and review contract quality.',
    displayOrder: 8,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.30 },
      { source: 'BQS', signal: 'recurring_revenue', weight: 0.35 },
      { source: 'BQS', signal: 'customer_concentration', weight: 0.35 },
    ],
    impactBaseLow: 75_000,
    impactBaseHigh: 300_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to revenue quality analysis.', order: 1 },
      { title: 'Why Revenue Quality Matters', description: 'How revenue quality drives valuation multiples.', order: 2 },
      { title: 'Revenue Quality Spectrum', description: 'Classify revenue into five quality tiers.', order: 3 },
      { title: 'Recurring vs Non-Recurring', description: 'Calculate and improve your recurring revenue ratio.', order: 4 },
      { title: 'Customer Concentration', description: 'Assess concentration risk from top customers.', order: 5 },
      { title: 'Revenue Diversification', description: 'Score diversification across multiple dimensions.', order: 6 },
      { title: 'Contract Quality', description: 'Evaluate contract terms and renewal rates.', order: 7 },
      { title: 'Revenue Trend Analysis', description: 'Build a 3-year revenue trend analysis.', order: 8 },
      { title: 'Common Mistakes', description: 'Revenue quality mistakes that destroy deal value.', order: 9 },
      { title: 'Dashboard', description: 'Revenue quality dashboard with composite scores.', order: 10 },
    ],
  },
  {
    slug: 'working-capital-optimization',
    title: 'Working Capital Optimization',
    category: 'FINANCIAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 6,
    description: 'Understand working capital fundamentals, calculate net working capital, then optimize accounts receivable, inventory, and accounts payable to improve cash conversion and minimize capital trapped in the deal.',
    displayOrder: 9,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.70 },
      { source: 'BQS', signal: 'margin_adjustment', weight: 0.30 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to working capital optimization.', order: 1 },
      { title: 'WC Fundamentals', description: 'Core concepts of working capital.', order: 2 },
      { title: 'Why Buyers Care', description: 'How the peg mechanism works in deals.', order: 3 },
      { title: 'Calculate Your NWC', description: 'Calculate net working capital.', order: 4 },
      { title: 'The Working Capital Peg', description: 'Understand and calculate the peg.', order: 5 },
      { title: 'Optimization Strategies', description: 'Strategies to optimize working capital.', order: 6 },
      { title: 'Accounts Receivable', description: 'Optimize AR through better terms and collection.', order: 7 },
      { title: 'Inventory', description: 'Optimize inventory management.', order: 8 },
      { title: 'Accounts Payable', description: 'Optimize AP through better terms and timing.', order: 9 },
      { title: 'Common Mistakes', description: 'Working capital mistakes that cost sellers money.', order: 10 },
      { title: 'Dashboard', description: 'Working capital optimization dashboard.', order: 11 },
    ],
  },
  {
    slug: 'debt-liability-cleanup',
    title: 'Debt & Liability Cleanup',
    category: 'FINANCIAL',
    difficulty: 'MEDIUM',
    durationLow: 2,
    durationHigh: 6,
    description: 'Resolve every liability before a buyer finds it. Inventory all debt, assess contingent liabilities and legal exposure, review insurance, and build a resolution plan.',
    displayOrder: 10,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.40 },
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.30 },
      { source: 'RSS', signal: 'Documentation Quality', weight: 0.30 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to liability cleanup.', order: 1 },
      { title: 'Debt Inventory', description: 'Comprehensive inventory of all debt instruments.', order: 2 },
      { title: 'Liability Cleanup Checklist', description: 'Systematic checklist of liabilities to resolve.', order: 3 },
      { title: 'Contingent Liabilities & Legal Exposure', description: 'Assess pending litigation, environmental, and regulatory risks.', order: 4 },
      { title: 'Tax & Legal', description: 'Review tax obligations and legal compliance.', order: 5 },
      { title: 'Insurance Review', description: 'Review all insurance policies for gaps.', order: 6 },
      { title: 'Resolution Plan', description: 'Prioritized plan to resolve each liability.', order: 7 },
      { title: 'Liability Readiness Scorecard', description: 'Overall liability readiness score.', order: 8 },
    ],
  },
  {
    slug: 'three-year-financial-projection',
    title: 'Three-Year Financial Projection Model',
    category: 'FINANCIAL',
    difficulty: 'VERY_HIGH',
    durationLow: 1,
    durationHigh: 3,
    description: 'Build a credible three-year financial projection. Document assumptions, project revenue by stream, model expense trajectories, plan capital expenditures, and run sensitivity analysis.',
    displayOrder: 11,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.50 },
      { source: 'RSS', signal: 'Documentation Quality', weight: 0.25 },
      { source: 'BQS', signal: 'growth_adjustment', weight: 0.25 },
    ],
    impactBaseLow: 75_000,
    impactBaseHigh: 300_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to financial projections.', order: 1 },
      { title: 'Document Your Assumptions', description: 'Document every assumption with market data support.', order: 2 },
      { title: 'Revenue Projections', description: 'Project revenue by stream with growth rates.', order: 3 },
      { title: 'Expense Projections', description: 'Model expense trajectories and margin assumptions.', order: 4 },
      { title: 'CapEx & Cash Flow', description: 'Plan capital expenditures and model free cash flow.', order: 5 },
      { title: 'Sensitivity Analysis', description: 'Run bull/base/bear scenarios.', order: 6 },
      { title: 'Three-Year Projection Summary', description: 'Complete projection summary.', order: 7 },
    ],
  },
  {
    slug: 'margin-improvement-program',
    title: 'Margin Improvement Program',
    category: 'FINANCIAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 12,
    description: 'Systematically improve EBITDA margins using a 5-lever framework covering cost structure, supplier renegotiation, product line pruning, pricing discipline, and operational efficiency.',
    displayOrder: 28,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.30 },
      { source: 'BQS', signal: 'margin_adjustment', weight: 0.50 },
      { source: 'BQS', signal: 'size_discount', weight: 0.20 },
    ],
    impactBaseLow: 100_000,
    impactBaseHigh: 400_000,
    phases: [
      { title: 'Welcome', description: 'Overview of margin improvement impact on value.', order: 1 },
      { title: 'Why Margins Drive Value', description: 'The double impact through EBITDA growth and multiple expansion.', order: 2 },
      { title: 'The 5-Lever Framework', description: 'Overview of five systematic levers.', order: 3 },
      { title: 'Cost Structure Audit', description: 'Line-item audit with peer benchmarking.', order: 4 },
      { title: 'Supplier Renegotiation', description: 'Strategies for renegotiating supplier contracts.', order: 5 },
      { title: 'Product Line Review', description: 'Identify and prune low-margin products.', order: 6 },
      { title: 'Pricing Discipline', description: 'Eliminate unnecessary discounting.', order: 7 },
      { title: 'Operational Efficiency', description: 'Process automation and waste reduction.', order: 8 },
      { title: 'Flow-Through Analysis', description: 'Track how savings flow through to EBITDA.', order: 9 },
      { title: 'Pitfall Avoidance', description: 'Mistakes that backfire or erode value.', order: 10 },
      { title: 'Implementation Timeline', description: 'Phased plan with milestones.', order: 11 },
      { title: 'Your Margin Plan', description: 'Summary of opportunities and execution roadmap.', order: 12 },
    ],
  },
  {
    slug: 'pricing-strategy-optimization',
    title: 'Pricing Strategy Optimization',
    category: 'FINANCIAL',
    difficulty: 'MEDIUM',
    durationLow: 3,
    durationHigh: 12,
    description: 'Optimize pricing strategy in the 12-24 months before exit. A 1% price increase drops 8-12% to EBITDA through value-based pricing, discount recovery, premium tier design, and competitive positioning.',
    displayOrder: 29,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.30 },
      { source: 'DRS', signal: 'MARKET', weight: 0.30 },
      { source: 'BQS', signal: 'margin_adjustment', weight: 0.40 },
    ],
    impactBaseLow: 75_000,
    impactBaseHigh: 300_000,
    phases: [
      { title: 'Welcome', description: 'Overview of pricing as the most powerful EBITDA lever.', order: 1 },
      { title: 'Why Pricing Matters', description: 'The math behind pricing leverage.', order: 2 },
      { title: 'Pricing Paradigms', description: 'Compare cost-plus, competitive, and value-based.', order: 3 },
      { title: 'Value-Based Pricing', description: 'Implement pricing tied to customer outcomes.', order: 4 },
      { title: 'Discount Recovery', description: 'Audit and recover margin leakage.', order: 5 },
      { title: 'Premium Tier Design', description: 'Design premium tiers that capture more value.', order: 6 },
      { title: 'Pricing Analytics', description: 'Build pricing analytics for elasticity and willingness to pay.', order: 7 },
      { title: 'Competitive Position', description: 'Map competitive pricing landscape.', order: 8 },
      { title: 'Price Increase Plan', description: 'Plan and execute price increases.', order: 9 },
      { title: 'Common Mistakes', description: 'Avoid uniform increases and fear-based underpricing.', order: 10 },
      { title: 'Implementation Timeline', description: 'Phased timeline for pricing changes.', order: 11 },
      { title: 'Summary & Export', description: 'Summary and projected EBITDA impact.', order: 12 },
    ],
  },

  // ==========================================
  // OPERATIONAL (03, 12, 13, 15, 16, 17, 18, 40)
  // ==========================================
  {
    slug: 'owner-dependency-reduction',
    title: 'Owner Dependency Reduction',
    category: 'OPERATIONAL',
    difficulty: 'VERY_HIGH',
    durationLow: 6,
    durationHigh: 18,
    description: 'Systematically reduce the business\'s dependence on you by diagnosing four types of dependency, mapping every function you perform, and executing a structured extraction process.',
    displayOrder: 3,
    triggers: [
      { source: 'RSS', signal: 'Key-Person Risk', weight: 0.40 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.35 },
      { source: 'BQS', signal: 'owner_dependency', weight: 0.25 },
    ],
    impactBaseLow: 150_000,
    impactBaseHigh: 500_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to owner dependency reduction.', order: 1 },
      { title: 'The Problem', description: 'How owner dependency develops and destroys value.', order: 2 },
      { title: 'Valuation Impact', description: 'Quantify how dependency reduces your multiple.', order: 3 },
      { title: 'Your Dependency Score', description: 'Score your dependency across ten dimensions.', order: 4 },
      { title: 'Four Types of Dependency', description: 'Diagnose relationship, knowledge, decision, and task dependency.', order: 5 },
      { title: 'Function Inventory', description: 'Map every function you perform.', order: 6 },
      { title: 'Extraction Framework', description: 'Follow the 5-step extraction process.', order: 7 },
      { title: 'Delegation Playbook', description: 'Practical delegation with training plans.', order: 8 },
      { title: 'Authority Matrix', description: 'Define decision-making authority levels.', order: 9 },
      { title: 'Process Documentation', description: 'Document critical processes.', order: 10 },
      { title: 'Absence Tests', description: 'Run graduated absence tests.', order: 11 },
      { title: 'Common Mistakes', description: 'Owner extraction mistakes.', order: 12 },
      { title: 'Implementation', description: 'Multi-month implementation timeline.', order: 13 },
      { title: 'Your Summary', description: 'Owner dependency reduction scorecard.', order: 14 },
    ],
  },
  {
    slug: 'management-team-bench-strength',
    title: 'Management Team Bench Strength',
    category: 'OPERATIONAL',
    difficulty: 'VERY_HIGH',
    durationLow: 12,
    durationHigh: 24,
    description: 'Evaluate your management team across buyer-critical dimensions, identify key-person concentration risk, and build a plan to develop bench strength that makes you optional.',
    displayOrder: 12,
    triggers: [
      { source: 'RSS', signal: 'Key-Person Risk', weight: 0.35 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.40 },
      { source: 'BQS', signal: 'owner_dependency', weight: 0.25 },
    ],
    impactBaseLow: 100_000,
    impactBaseHigh: 400_000,
    phases: [
      { title: 'Team Audit', description: 'Map leadership roles and identify owner-held functions.', order: 1 },
      { title: 'Role-by-Role Assessment', description: 'Score each role across 5 buyer-critical dimensions.', order: 2 },
      { title: 'Gap Analysis & Prioritization', description: 'Identify critical gaps and prioritize remediation.', order: 3 },
      { title: 'Retention Planning', description: 'Design retention strategies for key personnel.', order: 4 },
      { title: 'Action Plan', description: 'Build a concrete action plan with timelines.', order: 5 },
      { title: 'Bench Strength Scorecard', description: 'Dashboard summarizing team readiness.', order: 6 },
    ],
  },
  {
    slug: 'key-employee-retention',
    title: 'Key Employee Retention & Risk Mitigation',
    category: 'OPERATIONAL',
    difficulty: 'HIGH',
    durationLow: 6,
    durationHigh: 18,
    description: 'Identify critical personnel, assess flight risk, design retention programs with stay bonuses, capture institutional knowledge, and build communication strategies to protect human capital through a transaction.',
    displayOrder: 13,
    triggers: [
      { source: 'RSS', signal: 'Key-Person Risk', weight: 0.45 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.35 },
      { source: 'BQS', signal: 'owner_dependency', weight: 0.20 },
    ],
    impactBaseLow: 75_000,
    impactBaseHigh: 300_000,
    phases: [
      { title: 'Key Employee Criticality Matrix', description: 'Score key employees by criticality.', order: 1 },
      { title: 'Flight Risk Assessment', description: 'Evaluate departure likelihood.', order: 2 },
      { title: 'Risk Heat Map', description: 'Visualize criticality vs. flight risk.', order: 3 },
      { title: 'Retention Program Design', description: 'Design retention programs across four pillars.', order: 4 },
      { title: 'Stay Bonus Structures', description: 'Structure stay bonuses and incentive packages.', order: 5 },
      { title: 'Institutional Knowledge Capture', description: 'Systematically document tribal knowledge.', order: 6 },
      { title: 'Communication Strategy & Action Plan', description: 'Build tiered disclosure plans.', order: 7 },
    ],
  },
  {
    slug: 'sops-process-documentation',
    title: 'SOPs & Process Documentation',
    category: 'OPERATIONAL',
    difficulty: 'HIGH',
    durationLow: 6,
    durationHigh: 12,
    description: 'Inventory business processes, assess documentation maturity, prioritize critical SOPs, and build a documentation system that makes the business transferable.',
    displayOrder: 15,
    triggers: [
      { source: 'RSS', signal: 'Documentation Quality', weight: 0.35 },
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.40 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.25 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Documentation Maturity', description: 'Assess current documentation maturity.', order: 1 },
      { title: 'Process Inventory', description: 'Catalog all critical business processes.', order: 2 },
      { title: 'Priority Framework', description: 'Prioritize processes by buyer impact.', order: 3 },
      { title: 'Documentation Standards', description: 'Establish standards and templates.', order: 4 },
      { title: 'SOP Template Builder', description: 'Build standardized SOP templates.', order: 5 },
      { title: 'Process Mapping', description: 'Create visual process maps.', order: 6 },
      { title: 'Ownership & Maintenance', description: 'Assign document owners and review cadences.', order: 7 },
      { title: 'Transferability Checklist', description: 'Verify documentation meets diligence standards.', order: 8 },
      { title: 'Implementation Timeline', description: 'Phased rollout plan.', order: 9 },
      { title: 'Documentation Dashboard', description: 'Documentation score and transferability rating.', order: 10 },
    ],
  },
  {
    slug: 'technology-systems-audit',
    title: 'Technology & Systems Audit',
    category: 'OPERATIONAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 9,
    description: 'Audit your technology stack across 7 domains, identify technical debt and shadow IT, assess cybersecurity posture, and prepare technology documentation for diligence.',
    displayOrder: 16,
    triggers: [
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.60 },
      { source: 'BQS', signal: 'margin_adjustment', weight: 0.40 },
    ],
    impactBaseLow: 40_000,
    impactBaseHigh: 150_000,
    phases: [
      { title: 'Audit Framework', description: 'Assess 7 technology domains.', order: 1 },
      { title: 'Tech Stack Inventory', description: 'Catalog all technology systems.', order: 2 },
      { title: 'Technical Debt Register', description: 'Identify and quantify technical debt.', order: 3 },
      { title: 'Shadow IT Discovery', description: 'Discover unauthorized tools and systems.', order: 4 },
      { title: 'Data Centralization & Governance', description: 'Assess data storage and governance.', order: 5 },
      { title: 'Cybersecurity Baseline', description: 'Evaluate security controls.', order: 6 },
      { title: 'Software Licensing & Compliance', description: 'Verify software licenses.', order: 7 },
      { title: 'Due Diligence Preparation', description: 'Prepare technology documentation.', order: 8 },
      { title: 'Technology Readiness Dashboard', description: 'Tech readiness score and security status.', order: 9 },
    ],
  },
  {
    slug: 'vendor-supply-chain-resilience',
    title: 'Vendor & Supply Chain Resilience',
    category: 'OPERATIONAL',
    difficulty: 'HIGH',
    durationLow: 6,
    durationHigh: 12,
    description: 'Analyze vendor concentration and criticality, assess contract terms, develop alternative sourcing strategies, and build a supply chain risk register.',
    displayOrder: 17,
    triggers: [
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.60 },
      { source: 'DRS', signal: 'MARKET', weight: 0.40 },
    ],
    impactBaseLow: 40_000,
    impactBaseHigh: 150_000,
    phases: [
      { title: 'Supplier Concentration Analysis', description: 'Measure vendor dependency metrics.', order: 1 },
      { title: 'Vendor Criticality Matrix', description: 'Map vendors by impact and replaceability.', order: 2 },
      { title: 'Contract Terms Assessment', description: 'Review vendor contracts for assignability.', order: 3 },
      { title: 'Alternative Sourcing Strategy', description: 'Identify alternative vendors.', order: 4 },
      { title: 'Multi-Year Agreements', description: 'Secure long-term agreements.', order: 5 },
      { title: 'Supply Chain Risk Register', description: 'Formal risk assessment.', order: 6 },
      { title: 'Vendor Relationship Management', description: 'Establish vendor management processes.', order: 7 },
      { title: 'Cost Structure & Margin Protection', description: 'Analyze cost trends and protect margins.', order: 8 },
      { title: 'Logistics & Fulfillment Review', description: 'Assess logistics and delivery performance.', order: 9 },
      { title: 'Common Mistakes', description: 'Common supply chain mistakes.', order: 10 },
      { title: 'Supply Chain Resilience Report', description: 'Resilience score and report.', order: 11 },
    ],
  },
  {
    slug: 'facility-lease-review',
    title: 'Facility & Lease Review',
    category: 'OPERATIONAL',
    difficulty: 'MEDIUM',
    durationLow: 3,
    durationHigh: 6,
    description: 'Inventory all physical locations, analyze lease assignability and terms, assess facility condition and environmental risks, and verify zoning compliance.',
    displayOrder: 18,
    triggers: [
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.50 },
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.50 },
    ],
    impactBaseLow: 30_000,
    impactBaseHigh: 120_000,
    phases: [
      { title: 'Facility Inventory', description: 'Catalog every physical location.', order: 1 },
      { title: 'Lease Terms & Assignability', description: 'Review lease assignment and consent requirements.', order: 2 },
      { title: 'Owned vs. Leased Property', description: 'Analyze ownership structure.', order: 3 },
      { title: 'Equipment Leases & Capital Equipment', description: 'Inventory equipment leases.', order: 4 },
      { title: 'Facility Condition Assessment', description: 'Evaluate building systems and deferred maintenance.', order: 5 },
      { title: 'Environmental Concerns', description: 'Identify environmental risks.', order: 6 },
      { title: 'Zoning, Permits & Compliance', description: 'Verify zoning and permit compliance.', order: 7 },
      { title: 'Buyer Presentation & Data Room', description: 'Prepare facility documentation.', order: 8 },
      { title: 'Common Mistakes', description: 'Common facility-related mistakes.', order: 9 },
      { title: 'Facility & Lease Readiness Report', description: 'Facility readiness score.', order: 10 },
    ],
  },
  {
    slug: 'business-continuity-disaster-recovery',
    title: 'Business Continuity & Disaster Recovery',
    category: 'OPERATIONAL',
    difficulty: 'HIGH',
    durationLow: 2,
    durationHigh: 4,
    description: 'Build operational resilience that buyers evaluate during due diligence. Assess critical system failures, key person departures, and external shocks, then develop recovery strategies.',
    displayOrder: 40,
    triggers: [
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.50 },
      { source: 'RSS', signal: 'Key-Person Risk', weight: 0.30 },
      { source: 'RSS', signal: 'Documentation Quality', weight: 0.20 },
    ],
    impactBaseLow: 30_000,
    impactBaseHigh: 120_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to BC/DR as exit planning.', order: 1 },
      { title: 'Why BC/DR Is Exit Planning', description: 'How buyers evaluate resilience.', order: 2 },
      { title: 'Critical System Failures', description: 'Assess recovery objectives and backup readiness.', order: 3 },
      { title: 'Key Person Departures', description: 'Score dependency levels for key roles.', order: 4 },
      { title: 'External Shocks', description: 'Score readiness for recession, pandemic, and disaster.', order: 5 },
      { title: 'Supply Chain Resilience', description: 'Evaluate supply chain concentration.', order: 6 },
      { title: 'IT Disaster Recovery', description: 'Plan for restoring technology systems.', order: 7 },
      { title: 'Business Interruption Insurance', description: 'Understand BI insurance coverage.', order: 8 },
      { title: 'Crisis Communication', description: 'Establish communication protocols.', order: 9 },
      { title: 'Testing & Improvement', description: 'Test plans and train teams.', order: 10 },
      { title: 'BC/DR Readiness Dashboard', description: 'Overall BC/DR readiness score.', order: 11 },
    ],
  },

  // ==========================================
  // LEGAL (19-25, 39, 41)
  // ==========================================
  {
    slug: 'corporate-housekeeping',
    title: 'Corporate Housekeeping & Entity Compliance',
    category: 'LEGAL',
    difficulty: 'MEDIUM',
    durationLow: 3,
    durationHigh: 9,
    description: 'Verify entity good standing, reconcile capitalization tables, audit governance documents, build due diligence checklists, and cure corporate deficiencies before entering a data room.',
    displayOrder: 19,
    triggers: [
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.50 },
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.50 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Entity Good Standing & Annual Filings', description: 'Verify good standing in all jurisdictions.', order: 1 },
      { title: 'Capitalization Table Cleanup', description: 'Reconcile ownership records and cap table.', order: 2 },
      { title: 'Board Minutes, Agreements & Governance', description: 'Audit governance documents.', order: 3 },
      { title: 'Due Diligence Document Checklist', description: 'Build comprehensive document checklist.', order: 4 },
      { title: 'Common Deficiencies & How to Cure Them', description: 'Step-by-step cure procedures.', order: 5 },
      { title: 'Shareholder & Member Dispute Log', description: 'Document disputes and resolution status.', order: 6 },
      { title: 'Corporate Cleanup Action Plan', description: 'Prioritized action plan with timelines.', order: 7 },
      { title: 'Readiness Assessment', description: 'Corporate readiness score.', order: 8 },
    ],
  },
  {
    slug: 'ip-audit-protection',
    title: 'Intellectual Property Audit & Protection',
    category: 'LEGAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 12,
    description: 'Inventory all IP assets across 8 categories, verify ownership and assignment agreements, evaluate trademark and patent protection, and secure your IP portfolio.',
    displayOrder: 20,
    triggers: [
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.40 },
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.30 },
      { source: 'DRS', signal: 'MARKET', weight: 0.30 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Comprehensive IP Inventory', description: 'Catalog every IP asset.', order: 1 },
      { title: 'Ownership & Assignment Agreements', description: 'Audit assignment agreements.', order: 2 },
      { title: 'Trademark Strategy & Registration', description: 'Evaluate trademark portfolio.', order: 3 },
      { title: 'Patent, Trade Secret & Copyright Protection', description: 'Assess patent and copyright registrations.', order: 4 },
      { title: 'Software, Technology & Digital Assets', description: 'Review software ownership and open source.', order: 5 },
      { title: 'IP Deficiencies & Remediation', description: 'Identify gaps and build remediation plans.', order: 6 },
      { title: 'IP Valuation Considerations', description: 'How IP contributes to enterprise value.', order: 7 },
      { title: 'IP Protection Action Plan', description: 'Prioritized action plan to secure IP.', order: 8 },
      { title: 'IP Readiness Assessment', description: 'IP protection score.', order: 9 },
    ],
  },
  {
    slug: 'contract-agreement-review',
    title: 'Contract & Agreement Review',
    category: 'LEGAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 12,
    description: 'Inventory all material contracts, assess customer, vendor, partnership, and employment agreements for deal risks, identify change-of-control provisions, and build a remediation plan.',
    displayOrder: 21,
    triggers: [
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.40 },
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.30 },
      { source: 'RSS', signal: 'Customer Concentration', weight: 0.30 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Why Contracts Matter in M&A', description: 'How buyers evaluate your contract portfolio.', order: 1 },
      { title: 'Material Contract Inventory', description: 'Comprehensive contract inventory.', order: 2 },
      { title: 'Customer Agreements & Revenue Contracts', description: 'Analyze customer contracts.', order: 3 },
      { title: 'Vendor & Supplier Agreements', description: 'Review vendor contracts.', order: 4 },
      { title: 'Partnership & Joint Venture Agreements', description: 'Assess partnership agreements.', order: 5 },
      { title: 'Employment & Contractor Agreements', description: 'Review employment contracts and IP assignments.', order: 6 },
      { title: 'Change-of-Control & Anti-Assignment', description: 'Identify change-of-control triggers.', order: 7 },
      { title: '12-Month Action Plan', description: 'Phased remediation plan.', order: 8 },
      { title: 'Contract Readiness Dashboard', description: 'Contract readiness score.', order: 9 },
    ],
  },
  {
    slug: 'employment-hr-compliance',
    title: 'Employment & HR Compliance',
    category: 'LEGAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 9,
    description: 'Audit employment practices for legal compliance including worker classification, handbook policies, benefit plans, wage and hour rules, and COBRA/WARN Act obligations.',
    displayOrder: 22,
    triggers: [
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.50 },
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.30 },
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.20 },
    ],
    impactBaseLow: 40_000,
    impactBaseHigh: 150_000,
    phases: [
      { title: 'Why Employment Compliance Matters', description: 'Impact on deal value and buyer risk.', order: 1 },
      { title: 'Employee Classification: W-2 vs. 1099', description: 'Audit worker classifications.', order: 2 },
      { title: 'Employee Handbook & Policy Compliance', description: 'Review handbook for required policies.', order: 3 },
      { title: 'Benefit Plan Documentation & ERISA', description: 'Verify benefit plan compliance.', order: 4 },
      { title: 'Wage & Hour Compliance', description: 'Audit overtime and wage compliance.', order: 5 },
      { title: 'I-9 Verification & Immigration', description: 'Review I-9 documentation.', order: 6 },
      { title: 'EEOC, Anti-Discrimination & Harassment', description: 'Assess anti-discrimination policies.', order: 7 },
      { title: 'COBRA, WARN Act & Transaction Obligations', description: 'Evaluate COBRA and WARN Act requirements.', order: 8 },
      { title: 'HR Compliance Dashboard', description: 'Compliance score and exposure calculator.', order: 9 },
    ],
  },
  {
    slug: 'regulatory-licensing-compliance',
    title: 'Regulatory & Licensing Compliance',
    category: 'LEGAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 9,
    description: 'Audit every license, permit, and regulatory approval to determine transferability, identify compliance gaps, and build a diligence-ready regulatory package.',
    displayOrder: 23,
    triggers: [
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.50 },
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.50 },
    ],
    impactBaseLow: 40_000,
    impactBaseHigh: 150_000,
    phases: [
      { title: 'Welcome', description: 'Overview of regulatory compliance importance.', order: 1 },
      { title: 'Transaction Impact', description: 'How buyers evaluate regulatory risk.', order: 2 },
      { title: 'License Inventory', description: 'Catalog all licenses and permits.', order: 3 },
      { title: 'Transferability', description: 'Assess which licenses transfer automatically.', order: 4 },
      { title: 'Industry Deep Dive', description: 'Industry-specific regulatory requirements.', order: 5 },
      { title: 'Gap Analysis', description: 'Identify and prioritize compliance gaps.', order: 6 },
      { title: 'Remediation Plan', description: 'Plan to close compliance gaps.', order: 7 },
      { title: 'Data Room Prep', description: 'Prepare regulatory documents for data room.', order: 8 },
      { title: 'Agency Communications', description: 'Plan agency communications.', order: 9 },
      { title: 'Deal Killers', description: 'Common regulatory mistakes that kill deals.', order: 10 },
      { title: 'Summary & Scores', description: 'Overall compliance readiness score.', order: 11 },
    ],
  },
  {
    slug: 'environmental-insurance-review',
    title: 'Environmental & Insurance Review',
    category: 'LEGAL',
    difficulty: 'HIGH',
    durationLow: 2,
    durationHigh: 6,
    description: 'Identify environmental liabilities and insurance coverage gaps that could exceed enterprise value or leave the seller exposed for years after closing.',
    displayOrder: 24,
    triggers: [
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.50 },
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.30 },
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.20 },
    ],
    impactBaseLow: 30_000,
    impactBaseHigh: 150_000,
    phases: [
      { title: 'Welcome', description: 'Overview of environmental and insurance risks.', order: 1 },
      { title: 'Why It Matters', description: 'How CERCLA liability and insurance gaps affect deals.', order: 2 },
      { title: 'Environmental Assessment', description: 'Evaluate environmental exposure.', order: 3 },
      { title: 'Phase I & Phase II ESAs', description: 'Determine if ESAs are needed.', order: 4 },
      { title: 'Insurance Coverage Review', description: 'Review all current insurance policies.', order: 5 },
      { title: 'Specialty Insurance', description: 'Evaluate reps & warranties insurance.', order: 6 },
      { title: 'Claims Resolution', description: 'Resolve open insurance claims.', order: 7 },
      { title: 'Tail Coverage Planning', description: 'Plan post-closing tail coverage.', order: 8 },
      { title: 'Common Mistakes', description: 'Common environmental and insurance pitfalls.', order: 9 },
      { title: 'Dashboard', description: 'Summary scores and remediation actions.', order: 10 },
    ],
  },
  {
    slug: 'data-privacy-cybersecurity-posture',
    title: 'Data Privacy & Cybersecurity Posture',
    category: 'LEGAL',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 9,
    description: 'Audit data practices, evaluate regulatory exposure, and build a diligence-ready cybersecurity posture covering data handling, breach risk, and privacy policies.',
    displayOrder: 25,
    triggers: [
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.40 },
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.30 },
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.30 },
    ],
    impactBaseLow: 40_000,
    impactBaseHigh: 150_000,
    phases: [
      { title: 'Welcome', description: 'How data privacy issues impact exit valuation.', order: 1 },
      { title: 'Data Handling Audit', description: 'Map data you collect, store, and share.', order: 2 },
      { title: 'Regulatory Exposure', description: 'Identify applicable privacy regulations.', order: 3 },
      { title: 'Cybersecurity Hygiene', description: 'Assess core cybersecurity practices.', order: 4 },
      { title: 'Incident Response', description: 'Evaluate incident response readiness.', order: 5 },
      { title: 'Breach Risk', description: 'Score overall breach risk.', order: 6 },
      { title: 'Vendor Agreements', description: 'Review data processing agreements.', order: 7 },
      { title: 'Privacy Policy', description: 'Audit privacy policy for compliance.', order: 8 },
      { title: 'Dashboard', description: 'Summary scores across all dimensions.', order: 9 },
    ],
  },
  {
    slug: 'involuntary-exit-preparedness',
    title: 'Involuntary Exit Preparedness',
    category: 'LEGAL',
    difficulty: 'HIGH',
    durationLow: 2,
    durationHigh: 4,
    description: 'Prepare for the 5 D\'s of involuntary exit: death, disability, divorce, disagreement, and distress. Covers buy-sell agreements, key-person insurance, and emergency succession.',
    displayOrder: 39,
    triggers: [
      { source: 'RSS', signal: 'Key-Person Risk', weight: 0.40 },
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.30 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.30 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to involuntary exit preparedness.', order: 1 },
      { title: 'The 5 D\'s', description: 'Death, disability, divorce, disagreement, and financial distress.', order: 2 },
      { title: 'Buy-Sell Agreements', description: 'Buy-sell agreement structures.', order: 3 },
      { title: 'Funding', description: 'Funding mechanisms for buy-sell agreements.', order: 4 },
      { title: 'Key-Person Insurance', description: 'Key-person insurance planning.', order: 5 },
      { title: 'Emergency Succession', description: 'Emergency succession plans.', order: 6 },
      { title: 'Business Continuity', description: 'Maintain continuity during crisis.', order: 7 },
      { title: 'Legal Documents', description: 'Powers of attorney and estate documents.', order: 8 },
      { title: 'Valuation Mechanisms', description: 'Establish valuation mechanisms for forced exit.', order: 9 },
      { title: 'Communication Protocols', description: 'Notification protocols for emergencies.', order: 10 },
      { title: 'Implementation', description: 'Implementation checklist.', order: 11 },
    ],
  },
  {
    slug: 'partner-shareholder-alignment',
    title: 'Partner & Shareholder Alignment',
    category: 'LEGAL',
    difficulty: 'VERY_HIGH',
    durationLow: 2,
    durationHigh: 6,
    description: 'Align multiple owners on exit timing, valuation, deal structure, and governance. Covers operating agreement review, buy-sell mechanisms, dispute resolution, and drag/tag provisions.',
    displayOrder: 41,
    triggers: [
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.40 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.30 },
      { source: 'RSS', signal: 'Legal/Tax Risk', weight: 0.30 },
    ],
    impactBaseLow: 75_000,
    impactBaseHigh: 300_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to the multi-owner alignment challenge.', order: 1 },
      { title: 'The Multi-Owner Challenge', description: 'Common multi-owner exit challenges.', order: 2 },
      { title: 'Timing & Readiness', description: 'Assess each partner\'s exit timing and readiness.', order: 3 },
      { title: 'Valuation Alignment', description: 'Align on valuation methodology.', order: 4 },
      { title: 'Deal Structure', description: 'Align on deal structure preferences.', order: 5 },
      { title: 'Agreements Review', description: 'Review shareholder and operating agreement provisions.', order: 6 },
      { title: 'Buy-Sell Mechanisms', description: 'Evaluate buy-sell mechanisms.', order: 7 },
      { title: 'Dispute Resolution', description: 'Select valuation dispute resolution methods.', order: 8 },
      { title: 'Voting & Drag/Tag', description: 'Clarify voting rights and drag-along/tag-along.', order: 9 },
      { title: 'When Partners Disagree', description: 'Navigate deadlock scenarios.', order: 10 },
      { title: 'Alignment Workshop', description: 'Conduct structured alignment workshop.', order: 11 },
      { title: 'Results & Action Plan', description: 'Alignment report with score and action items.', order: 12 },
    ],
  },

  // ==========================================
  // MARKET_GROWTH (14, 26, 27, 30, 44)
  // ==========================================
  {
    slug: 'customer-concentration-de-risking',
    title: 'Customer Concentration De-Risking',
    category: 'MARKET_GROWTH',
    difficulty: 'HIGH',
    durationLow: 12,
    durationHigh: 36,
    description: 'Measure customer concentration using HHI analysis, understand how buyers evaluate concentration risk, and build diversification strategies and contract protections.',
    displayOrder: 14,
    triggers: [
      { source: 'RSS', signal: 'Customer Concentration', weight: 0.45 },
      { source: 'BQS', signal: 'customer_concentration', weight: 0.55 },
    ],
    impactBaseLow: 100_000,
    impactBaseHigh: 400_000,
    phases: [
      { title: 'Customer Revenue Data', description: 'Enter customer revenue data for concentration metrics.', order: 1 },
      { title: 'Concentration Analysis', description: 'Calculate HHI index and revenue distribution.', order: 2 },
      { title: 'Buyer Perspective', description: 'How buyers and lenders evaluate concentration.', order: 3 },
      { title: 'Contract Protection Strategy', description: 'Strengthen contract terms with top customers.', order: 4 },
      { title: 'Diversification Strategy', description: 'Design customer acquisition strategy.', order: 5 },
      { title: 'Implementation Timeline', description: 'Phased timeline for diversification.', order: 6 },
      { title: 'Narrative & Action Plan', description: 'Craft the buyer presentation narrative.', order: 7 },
    ],
  },
  {
    slug: 'value-driver-acceleration',
    title: 'Value Driver Acceleration',
    category: 'MARKET_GROWTH',
    difficulty: 'HIGH',
    durationLow: 6,
    durationHigh: 24,
    description: 'Identify the 3-5 levers that move your valuation multiple, prioritize by ROI and timeline, and build a structured plan to maximize enterprise value.',
    displayOrder: 26,
    triggers: [
      { source: 'DRS', signal: 'MARKET', weight: 0.30 },
      { source: 'BQS', signal: 'growth_adjustment', weight: 0.30 },
      { source: 'BQS', signal: 'recurring_revenue', weight: 0.20 },
      { source: 'BQS', signal: 'margin_adjustment', weight: 0.20 },
    ],
    impactBaseLow: 100_000,
    impactBaseHigh: 500_000,
    phases: [
      { title: 'Welcome', description: 'How value drivers affect multiples.', order: 1 },
      { title: 'Value Driver Diagnostic', description: 'Score your 8 core value drivers.', order: 2 },
      { title: 'Recurring Revenue', description: 'Deep dive into revenue quality.', order: 3 },
      { title: 'Margins', description: 'Analyze margins relative to benchmarks.', order: 4 },
      { title: 'Management Depth', description: 'Assess management team strength.', order: 5 },
      { title: 'Customer Diversification', description: 'Evaluate customer concentration.', order: 6 },
      { title: 'Priority Matrix', description: 'ROI vs. timeline prioritization.', order: 7 },
      { title: 'Value Calculator', description: 'Model enterprise value impact.', order: 8 },
      { title: 'Acceleration Plan', description: '12-24 month execution roadmap.', order: 9 },
      { title: 'Dashboard', description: 'Summary scores and projected impact.', order: 10 },
    ],
  },
  {
    slug: 'strategic-growth-initiatives',
    title: 'Strategic Growth Initiatives',
    category: 'MARKET_GROWTH',
    difficulty: 'VERY_HIGH',
    durationLow: 6,
    durationHigh: 18,
    description: 'Identify, evaluate, and launch 1-2 strategic growth initiatives that show buyers the future they are buying, including new market entry, product extensions, and channel partnerships.',
    displayOrder: 27,
    triggers: [
      { source: 'DRS', signal: 'MARKET', weight: 0.40 },
      { source: 'BQS', signal: 'growth_adjustment', weight: 0.35 },
      { source: 'BQS', signal: 'recurring_revenue', weight: 0.25 },
    ],
    impactBaseLow: 100_000,
    impactBaseHigh: 400_000,
    phases: [
      { title: 'Welcome', description: 'Why demonstrable growth increases buyer willingness to pay.', order: 1 },
      { title: 'Why Growth Matters', description: 'How growth affects multiples and buyer confidence.', order: 2 },
      { title: 'Initiative Evaluation', description: 'Evaluate four growth initiative types.', order: 3 },
      { title: 'New Market Entry', description: 'Plan entry into adjacent markets.', order: 4 },
      { title: 'Product Extension', description: 'Design upsell and cross-sell strategies.', order: 5 },
      { title: 'Channel Partnerships', description: 'Build referral and reseller partnerships.', order: 6 },
      { title: 'Geographic Expansion', description: 'Plan domestic or international expansion.', order: 7 },
      { title: '90-Day Sprint', description: 'Create a focused 90-day sprint plan.', order: 8 },
      { title: 'Pitfall Avoidance', description: 'Common mistakes that undermine growth before exit.', order: 9 },
      { title: 'Implementation Timeline', description: 'Full implementation timeline.', order: 10 },
      { title: 'Your Growth Plan', description: 'Summary of initiatives and execution roadmap.', order: 11 },
    ],
  },
  {
    slug: 'brand-market-position-strengthening',
    title: 'Brand & Market Position Strengthening',
    category: 'MARKET_GROWTH',
    difficulty: 'MEDIUM',
    durationLow: 6,
    durationHigh: 18,
    description: 'Build brand recognition, thought leadership, and market positioning that reduces acquisition costs, supports premium pricing, and gives buyers confidence.',
    displayOrder: 30,
    triggers: [
      { source: 'DRS', signal: 'MARKET', weight: 0.50 },
      { source: 'BQS', signal: 'growth_adjustment', weight: 0.25 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.25 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Welcome', description: 'How perception drives valuation.', order: 1 },
      { title: 'Why Brand Affects Value', description: 'Brand attributes and multiple premiums.', order: 2 },
      { title: 'Brand Audit', description: 'Audit current brand strength.', order: 3 },
      { title: 'Thought Leadership', description: 'Build industry visibility.', order: 4 },
      { title: 'Case Studies & Social Proof', description: 'Develop social proof assets.', order: 5 },
      { title: 'Awards & Recognition', description: 'Pursue industry awards.', order: 6 },
      { title: 'Digital Presence', description: 'Strengthen website and online reputation.', order: 7 },
      { title: 'Market Positioning', description: 'Define competitive differentiation.', order: 8 },
      { title: 'Brand Independence', description: 'Reduce owner-dependence of the brand.', order: 9 },
      { title: 'Common Mistakes', description: 'Brand-building mistakes to avoid.', order: 10 },
      { title: 'Dashboard', description: 'Brand strength scores.', order: 11 },
    ],
  },
  {
    slug: 'market-timing-assessment',
    title: 'Market Timing Assessment',
    category: 'MARKET_GROWTH',
    difficulty: 'MEDIUM',
    durationLow: 1,
    durationHigh: 2,
    description: 'Assess whether market conditions favor selling now or holding. Evaluates macroeconomic indicators, industry M&A cycles, buyer appetite, and generates a sell vs. hold signal.',
    displayOrder: 44,
    triggers: [
      { source: 'DRS', signal: 'MARKET', weight: 0.50 },
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.30 },
      { source: 'BQS', signal: 'size_discount', weight: 0.20 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Welcome', description: 'The best time to sell is when you do not have to.', order: 1 },
      { title: 'Macro Indicators', description: 'Evaluate macroeconomic indicators.', order: 2 },
      { title: 'Industry Cycles', description: 'Industry-specific M&A cycles.', order: 3 },
      { title: 'Buyer Appetite', description: 'Assess current buyer appetite indicators.', order: 4 },
      { title: 'Market Scorecard', description: 'Score market timing factors.', order: 5 },
      { title: 'Sell vs. Hold', description: 'Use the sell vs. hold decision framework.', order: 6 },
      { title: 'Comparable Deals', description: 'Track comparable transactions.', order: 7 },
      { title: 'Monthly Tracker', description: 'Monthly intelligence dashboard.', order: 8 },
      { title: 'Timing Dashboard', description: 'Overall market timing assessment.', order: 9 },
    ],
  },

  // ==========================================
  // DEAL_PREP (31-38, 43)
  // ==========================================
  {
    slug: 'valuation-benchmarking',
    title: 'Valuation Benchmarking',
    category: 'DEAL_PREP',
    difficulty: 'MEDIUM',
    durationLow: 1,
    durationHigh: 3,
    description: 'Understand your business valuation using three professional methods, industry multiples, and premium/discount drivers to build a defensible valuation range.',
    displayOrder: 31,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.40 },
      { source: 'DRS', signal: 'MARKET', weight: 0.30 },
      { source: 'BQS', signal: 'size_discount', weight: 0.30 },
    ],
    impactBaseLow: 75_000,
    impactBaseHigh: 300_000,
    phases: [
      { title: 'Welcome', description: 'Overview of valuation benchmarking.', order: 1 },
      { title: 'Why Benchmarking Matters', description: 'Know your range before engaging buyers.', order: 2 },
      { title: 'Three Core Methods', description: 'Comparable transactions, DCF, and asset-based approaches.', order: 3 },
      { title: 'Industry Multiples', description: 'Apply industry-specific multiples.', order: 4 },
      { title: 'Premium vs. Discount', description: 'Factors that command premiums or trigger discounts.', order: 5 },
      { title: 'Normalize EBITDA', description: 'Calculate normalized EBITDA.', order: 6 },
      { title: 'Valuation Range Builder', description: 'Build a defensible valuation range.', order: 7 },
      { title: 'Mistakes & Professionals', description: 'Common valuation mistakes.', order: 8 },
      { title: 'Summary & Next Steps', description: 'Valuation range summary.', order: 9 },
    ],
  },
  {
    slug: 'deal-team-assembly',
    title: 'Deal Team Assembly',
    category: 'DEAL_PREP',
    difficulty: 'MEDIUM',
    durationLow: 1,
    durationHigh: 3,
    description: 'Evaluate, select, and coordinate the four core advisors (M&A attorney, transaction CPA, wealth manager, banker/broker) who typically add 20-40% to net proceeds.',
    displayOrder: 32,
    triggers: [
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.40 },
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.30 },
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.30 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Welcome', description: 'Why a well-assembled deal team is essential.', order: 1 },
      { title: 'Why You Need a Team', description: 'Self-assessment of vulnerability without advisors.', order: 2 },
      { title: 'Four Core Roles', description: 'Overview of essential advisory roles.', order: 3 },
      { title: 'M&A Attorney', description: 'Evaluate M&A attorneys.', order: 4 },
      { title: 'Transaction CPA', description: 'Evaluate CPAs on M&A experience.', order: 5 },
      { title: 'Wealth Manager', description: 'Evaluate wealth managers.', order: 6 },
      { title: 'Banker / Broker', description: 'Evaluate investment bankers and brokers.', order: 7 },
      { title: 'Fee Tracker', description: 'Track advisory fee structures.', order: 8 },
      { title: 'Coordination & Mistakes', description: 'Coordinate team and avoid mistakes.', order: 9 },
      { title: 'Summary & Next Steps', description: 'Deal team readiness summary.', order: 10 },
    ],
  },
  {
    slug: 'buyer-universe-mapping',
    title: 'Buyer Universe Mapping',
    category: 'DEAL_PREP',
    difficulty: 'HIGH',
    durationLow: 1,
    durationHigh: 3,
    description: 'Map the buyer universe across six buyer types, assess fit, build a prioritized buyer list, and create a structured outreach plan to maximize competitive tension.',
    displayOrder: 33,
    triggers: [
      { source: 'DRS', signal: 'MARKET', weight: 0.40 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.30 },
      { source: 'BQS', signal: 'size_discount', weight: 0.30 },
    ],
    impactBaseLow: 75_000,
    impactBaseHigh: 300_000,
    phases: [
      { title: 'Welcome', description: '3-5 competing buyers create optimal outcomes.', order: 1 },
      { title: 'Your Business Profile', description: 'Define characteristics that determine buyer fit.', order: 2 },
      { title: 'The Six Buyer Types', description: 'Strategic, PE, family office, MBO, individual, search fund.', order: 3 },
      { title: 'Buyer Fit Assessment', description: 'Score buyer type fit for your business.', order: 4 },
      { title: 'Price / Process / Probability', description: 'Compare buyer types across dimensions.', order: 5 },
      { title: 'Synergy & Premium Map', description: 'Map synergy potential by buyer type.', order: 6 },
      { title: 'Buyer Universe List', description: 'Build a prioritized list of specific buyers.', order: 7 },
      { title: 'Outreach Tracker', description: 'Track NDAs, CIMs, IOIs.', order: 8 },
      { title: 'Buyer Qualification', description: 'Qualify buyers on capability and intent.', order: 9 },
      { title: 'Common Mistakes Audit', description: 'Audit for common buyer search mistakes.', order: 10 },
      { title: 'Dashboard', description: 'Buyer universe summary.', order: 11 },
    ],
  },
  {
    slug: 'cim-preparation',
    title: 'CIM Preparation',
    category: 'DEAL_PREP',
    difficulty: 'HIGH',
    durationLow: 2,
    durationHigh: 4,
    description: 'Build a compelling Confidential Information Memorandum with audience analysis, section-by-section construction, financial presentation, growth story, and quality control.',
    displayOrder: 34,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.30 },
      { source: 'DRS', signal: 'MARKET', weight: 0.30 },
      { source: 'RSS', signal: 'Documentation Quality', weight: 0.40 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Welcome', description: 'Your CIM is your first impression with buyers.', order: 1 },
      { title: 'Know Your Audience', description: 'What different buyer types focus on.', order: 2 },
      { title: 'CIM Structure & TOC', description: 'Build professional CIM structure.', order: 3 },
      { title: 'Executive Summary', description: 'Craft the most critical section.', order: 4 },
      { title: 'Investment Highlights', description: 'Define 5-7 quantified highlights.', order: 5 },
      { title: 'Financial Presentation', description: 'Present financials where deals are won.', order: 6 },
      { title: 'The Growth Story', description: 'Present credible growth opportunities.', order: 7 },
      { title: 'Management Team', description: 'Address what happens after owner leaves.', order: 8 },
      { title: 'Competitive Positioning', description: 'Explain your moat.', order: 9 },
      { title: 'Common Mistakes Audit', description: 'Audit against six common CIM mistakes.', order: 10 },
      { title: 'Information Gathering', description: 'Track document collection.', order: 11 },
      { title: 'Final Review Checklist', description: 'Verify every item before distribution.', order: 12 },
      { title: 'CIM Readiness Dashboard', description: 'Overall CIM preparation score.', order: 13 },
    ],
  },
  {
    slug: 'data-room-construction',
    title: 'Data Room Construction',
    category: 'DEAL_PREP',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 6,
    description: 'Construct a buyer-ready virtual data room with proper folder structure, document quality standards, access controls, and a 6-month pre-build timeline.',
    displayOrder: 35,
    triggers: [
      { source: 'RSS', signal: 'Documentation Quality', weight: 0.50 },
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.25 },
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.25 },
    ],
    impactBaseLow: 30_000,
    impactBaseHigh: 120_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to building a buyer-ready data room.', order: 1 },
      { title: 'Why Data Rooms Matter', description: 'Data rooms matter more than you think.', order: 2 },
      { title: 'Platform Selection', description: 'Select the right VDR platform.', order: 3 },
      { title: 'Folder Structure', description: 'Build the master folder structure.', order: 4 },
      { title: 'Document Checklist', description: 'Track required documents.', order: 5 },
      { title: 'Quality Standards', description: 'Ensure professional document quality.', order: 6 },
      { title: 'Access Controls', description: 'Configure permission tiers.', order: 7 },
      { title: 'Pre-Build Timeline', description: '6-month population timeline.', order: 8 },
      { title: 'Common Mistakes', description: 'Common data room mistakes.', order: 9 },
      { title: 'Readiness Score', description: 'Diligence readiness assessment.', order: 10 },
      { title: 'Implementation Plan', description: 'Week-by-week implementation plan.', order: 11 },
      { title: 'Dashboard', description: 'Data room action plan and readiness.', order: 12 },
    ],
  },
  {
    slug: 'deal-structure-literacy',
    title: 'Deal Structure Literacy',
    category: 'DEAL_PREP',
    difficulty: 'HIGH',
    durationLow: 1,
    durationHigh: 2,
    description: 'Master deal structure components that determine how much you take home. Covers asset vs. stock sales, earnouts, seller notes, escrows, working capital, and reps and warranties.',
    displayOrder: 36,
    triggers: [
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.40 },
      { source: 'DRS', signal: 'LEGAL_TAX', weight: 0.40 },
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.20 },
    ],
    impactBaseLow: 75_000,
    impactBaseHigh: 300_000,
    phases: [
      { title: 'Welcome', description: 'Why structure matters more than price.', order: 1 },
      { title: 'Why Structure > Price', description: 'Deal structure often matters more than headline price.', order: 2 },
      { title: 'Asset vs. Stock Sale', description: 'Compare structures and tax implications.', order: 3 },
      { title: 'Earnouts', description: 'Earnout structure, risks, and negotiation.', order: 4 },
      { title: 'Seller Notes', description: 'Deferred consideration structures.', order: 5 },
      { title: 'Escrows & Holdbacks', description: 'Post-close claim protections.', order: 6 },
      { title: 'Working Capital', description: 'Working capital adjustments.', order: 7 },
      { title: 'Reps & Warranties', description: 'Representations and indemnification.', order: 8 },
      { title: 'Non-Competes', description: 'Non-compete and employment terms.', order: 9 },
      { title: 'Proceeds Waterfall', description: 'Calculate actual proceeds.', order: 10 },
      { title: 'Common Mistakes', description: 'Common deal structure mistakes.', order: 11 },
      { title: 'Offer Comparison', description: 'Compare multiple offers side-by-side.', order: 12 },
      { title: 'Dashboard', description: 'Deal structure action plan and literacy score.', order: 13 },
    ],
  },
  {
    slug: 'negotiation-preparation',
    title: 'Negotiation Preparation',
    category: 'DEAL_PREP',
    difficulty: 'VERY_HIGH',
    durationLow: 1,
    durationHigh: 3,
    description: 'Prepare for deal negotiations with BATNA assessment, walk-away terms, deal point classification, buyer analysis, tactical counter-strategies, concession tracking, and post-LOI strategy.',
    displayOrder: 37,
    triggers: [
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.30 },
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.30 },
      { source: 'DRS', signal: 'MARKET', weight: 0.20 },
      { source: 'DRS', signal: 'PERSONAL', weight: 0.20 },
    ],
    impactBaseLow: 100_000,
    impactBaseHigh: 500_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to negotiation preparation.', order: 1 },
      { title: 'BATNA Assessment', description: 'Define your best alternative.', order: 2 },
      { title: 'Walk-Away Terms', description: 'Establish clear walk-away terms.', order: 3 },
      { title: 'Deal Point Classification', description: 'Classify deal points by importance.', order: 4 },
      { title: 'Buyer Analysis', description: 'Analyze buyer motivations and constraints.', order: 5 },
      { title: 'Buyer Tactics & Counters', description: 'Common buyer tactics and counters.', order: 6 },
      { title: 'Negotiation Phases', description: 'Phases of deal negotiation.', order: 7 },
      { title: 'Emotional Dynamics', description: 'Manage emotional dynamics.', order: 8 },
      { title: 'Advisory Team', description: 'Coordinate your advisory team.', order: 9 },
      { title: 'Post-LOI Strategy', description: 'Strategy for the post-LOI phase.', order: 10 },
      { title: 'Concession Tracker', description: 'Track concessions given and received.', order: 11 },
      { title: 'Pre-Negotiation Checklist', description: 'Pre-negotiation checklist.', order: 12 },
      { title: 'Readiness Summary', description: 'Negotiation readiness score.', order: 13 },
    ],
  },
  {
    slug: 'transition-integration-planning',
    title: 'Transition & Integration Planning',
    category: 'DEAL_PREP',
    difficulty: 'HIGH',
    durationLow: 3,
    durationHigh: 6,
    description: 'Plan the post-close transition including employee and customer communication, operational milestones, knowledge transfer protocols, and seller involvement decisions.',
    displayOrder: 38,
    triggers: [
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.50 },
      { source: 'RSS', signal: 'Key-Person Risk', weight: 0.30 },
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.20 },
    ],
    impactBaseLow: 50_000,
    impactBaseHigh: 200_000,
    phases: [
      { title: 'Welcome', description: 'Introduction to transition planning.', order: 1 },
      { title: 'Pre-Close Planning', description: 'Plan well before closing day.', order: 2 },
      { title: 'Transition Framework', description: 'Three-phase arc: intensive, graduated, advisory-only.', order: 3 },
      { title: 'Employee Communication', description: 'Communication strategy to retain key people.', order: 4 },
      { title: 'Customer Notification', description: 'Plan customer notification.', order: 5 },
      { title: 'Vendor & Partner Transition', description: 'Manage vendor relationships.', order: 6 },
      { title: 'Operational Milestones', description: 'Define measurable handoff milestones.', order: 7 },
      { title: 'Knowledge Transfer', description: 'Systematically extract institutional knowledge.', order: 8 },
      { title: 'Seller Involvement', description: 'Decide on post-close involvement level.', order: 9 },
      { title: 'Integration Risks', description: 'Assess integration risks.', order: 10 },
      { title: 'Common Mistakes', description: 'Common transition mistakes.', order: 11 },
      { title: 'KT Schedule', description: 'Written knowledge transfer schedule.', order: 12 },
      { title: 'Readiness Summary', description: 'Transition readiness assessment.', order: 13 },
    ],
  },
  {
    slug: 'exit-timeline-milestone-tracker',
    title: 'Exit Timeline & Milestone Tracker',
    category: 'DEAL_PREP',
    difficulty: 'MEDIUM',
    durationLow: 1,
    durationHigh: 2,
    description: 'Set your target exit date and track progress across all 44 playbooks with a five-phase roadmap, readiness factor assessment, critical path dependencies, and quarterly review scorecards.',
    displayOrder: 43,
    triggers: [
      { source: 'DRS', signal: 'TRANSFERABILITY', weight: 0.30 },
      { source: 'DRS', signal: 'FINANCIAL', weight: 0.25 },
      { source: 'DRS', signal: 'OPERATIONAL', weight: 0.25 },
      { source: 'DRS', signal: 'PERSONAL', weight: 0.20 },
    ],
    impactBaseLow: 25_000,
    impactBaseHigh: 100_000,
    phases: [
      { title: 'Welcome', description: 'Your exit is a journey, not an event.', order: 1 },
      { title: 'Exit Date Setup', description: 'Set target exit date.', order: 2 },
      { title: 'Readiness Factors', description: 'Assess readiness factors.', order: 3 },
      { title: 'Phase Overview', description: 'Five-phase exit roadmap.', order: 4 },
      { title: 'Playbook Tracker', description: 'Track progress across all 44 playbooks.', order: 5 },
      { title: 'Dependencies', description: 'Map critical path dependencies.', order: 6 },
      { title: 'Deal Readiness', description: 'Complete deal readiness checklist.', order: 7 },
      { title: 'Quarterly Review', description: 'Quarterly review scorecards.', order: 8 },
      { title: 'Timeline Dashboard', description: 'Overall timeline dashboard.', order: 9 },
    ],
  },
]

// Helper: get playbooks by category
export function getPlaybooksByCategory(
  category: PlaybookCategory
): PlaybookDefinition[] {
  return playbookDefinitions.filter((p) => p.category === category)
}

// Helper: get a single playbook by slug
export function getPlaybookBySlug(
  slug: string
): PlaybookDefinition | undefined {
  return playbookDefinitions.find((p) => p.slug === slug)
}
